package de.bo.aid.boese.DB.util;

public class DefaultRuleConstants {

	public static String permission1 = "";
	public static String permission2 	= "<PERMISSION>"
											+ "<USER>1</USER>"
										+ "</PERMISSION>";
	public static String permission3 	= "<PERMISSION>"
											+ "<USER>1</USER>"
											+ "<GROUP>2</GROUP>"
										+ "</PERMISSION>";

	public static String condition1 = "";
	public static String condition2 = "<CONDITION>"
									+ 	"<AND>"
									+ 		"<COMPONENT>"
									+ 			"<ID>1</ID>"
									+ 			"<VALUE>"
									+ 				"<CONSTANT>21.1</CONSTANT>"
									+ 			"</VALUE>"
									+ 			"<RESET_VALUE>10</RESET_VALUE>"
									+ 			"<COMPARATOR>==</COMPARATOR>"
									+ 		"</COMPONENT>"
									+ 		"<COMPONENT>"
									+ 			"<ID>2</ID>"
									+ 			"<VALUE>"
									+ 				"<CONSTANT>11.1</CONSTANT>"
									+ 			"</VALUE>"
									+ 			"<RESET_VALUE>20</RESET_VALUE>"
									+ 			"<COMPARATOR>!=</COMPARATOR>"
									+ 		"</COMPONENT>"
									+ 	"</AND>"
									+ "</CONDITION>";
	public static String condition3 = "<CONDITION>"
									+ "<OR>"
									+ 	"<AND>"
									+ 		"<COMPONENT>"
									+ 			"<ID>1</ID>"
									+ 			"<VALUE>"
									+ 				"<CONSTANT>21.1</CONSTANT>"
									+ 			"</VALUE>"
									+ 			"<RESET_VALUE>10</RESET_VALUE>"
									+ 			"<COMPARATOR>==</COMPARATOR>"
									+ 		"</COMPONENT>"
									+ 		"<COMPONENT>"
									+ 			"<ID>2</ID>"
									+ 			"<VALUE>"
									+ 				"<CONSTANT>11.1</CONSTANT>"
									+ 			"</VALUE>"
									+ 			"<RESET_VALUE>20</RESET_VALUE>"
									+ 			"<COMPARATOR>!=</COMPARATOR>"
									+ 		"</COMPONENT>"
									+ 	"</AND>"
									+ 	"<AND>"
									+ 		"<COMPONENT>"
									+ 			"<ID>3</ID>"
									+ 			"<VALUE>"
									+ 				"<CONSTANT>31.5</CONSTANT>"
									+ 			"</VALUE>"
									+ 			"<RESET_VALUE>10</RESET_VALUE>"
									+ 			"<COMPARATOR>!=</COMPARATOR>"
									+ 		"</COMPONENT>"
									+ 		"<COMPONENT>"
									+ 			"<ID>4</ID>"
									+ 			"<VALUE>"
									+ 				"<CONSTANT>42.2</CONSTANT>"
									+ 			"</VALUE>"
									+ 			"<RESET_VALUE>20</RESET_VALUE>"
									+ 			"<COMPARATOR>==</COMPARATOR>"
									+ 		"</COMPONENT>"
									+ 	"</AND>"
									+ "</OR>"
									+ "</CONDITION>";

	public static String action1 = "";
	public static String action2 	= "<ACTION>"
									+ 	"<ACTOR>"
									+ 		"<ID>1</ID>"
									+ 		"<VALUE>"
									+ 			"<CONSTANT>1</CONSTANT>"
									+ 		"</VALUE>"
									+ 	"</ACTOR>"
									+ 	"<ACTOR>"
									+ 		"<ID>2</ID>"
									+ 		"<VALUE>"
									+ 			"<ADD>"
									+ 				"<CONSTANT>255</CONSTANT>"
									+ 				"<MUL>"
									+ 					"<CONSTANT>327675</CONSTANT>"
									+ 					"<SUB>"
									+ 						"<FIRST>"
									+ 							"<MUL>"
									+ 								"<CONSTANT>2</CONSTANT>"
									+ 								"<VARIABLE>3</VARIABLE>"
									+ 							"</MUL>"
									+ 						"</FIRST>"
									+ 					"<CONSTANT>9</CONSTANT>"
									+ 					"</SUB>"
									+ 				"</MUL>"
									+ 			"</ADD>"
									+ 		"</VALUE>"
									+ 	"</ACTOR>"
									+ "</ACTION>";
	public static String action3 	= "<Action>"
									+ 	"<ACTIVATE_RULE_ID>1</ACTIVATE_RULE_ID>"
									+ 	"<DEACTIVATE_RULE_ID>2</DEACTIVATE_RULE_ID>"
									+ "</Action>";
}
