/*             
 * 			  (                       
 *			 ( )\         (        (   
 *			 )((_)  (    ))\ (    ))\  
 *			((_)_   )\  /((_))\  /((_) 
 *			 | _ ) ((_)(_)) ((_)(_))   
 *			 | _ \/ _ \/ -_)(_-</ -_)  
 *			 |___/\___/\___|/__/\___|
 *       
 *           			;            
 *		      +        ;;;         + 
 *			  +       ;;;;;        + 
 *			  +      ;;;;;;;       + 
 *			  ++    ;;;;;;;;;     ++ 
 *			  +++++;;;;;;;;;;;+++++  
 *			   ++++;;;;;;;;;;;+++++  
 *				++;;;;;;;;;;;;;++    
 *			     ;;;;;;;;;;;;;;;     
 *			    ;;;;;;;;;;;;;;;;;     
 *				:::::::::::::::::    
 * 				:::::::::::::::::      
 *  			:::::::::::::::::    
 *   			::::::@@@@@::::::    
 *				:::::@:::::@:::::    
 *				::::@:::::::@::::    
 * 				:::::::::::::::::    
 *  			:::::::::::::::::      
 */



package de.bo.aid.boese.modelJPA;

import javax.persistence.Column;
import javax.persistence.Transient;

// TODO: Auto-generated Javadoc
/**
 * DeviceGroupId Model for Hibernate generated by hbm2java.
 */
public class DeviceServiceId implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	@Transient
	private static final long serialVersionUID = 1L;

	/** The Device id. */
	@Column(name = "deId", nullable = false)
	private int deId;
	
	/** The Service id. */
	@Column(name = "seId", nullable = false)
	private int seId;

	/**
	 * Instantiates a new device group id.
	 */
	public DeviceServiceId() {
	}

	/**
	 * Instantiates a new device group id.
	 *
	 * @param deId the Device id
	 * @param grId the Group id
	 */
	public DeviceServiceId(int deId, int seId) {
		this.deId = deId;
		this.seId = seId;
	}

	/**
	 * Gets the Device id.
	 *
	 * @return the Device id
	 */
	public int getDeId() {
		return this.deId;
	}

	/**
	 * Sets the Device id.
	 *
	 * @param deId the new Device id
	 */
	public void setDeId(int deId) {
		this.deId = deId;
	}

	/**
	 * Gets the Service id.
	 *
	 * @return the Service id
	 */
	public int getSeId() {
		return this.seId;
	}

	/**
	 * Sets the Service id.
	 *
	 * @param seId the new Service id
	 */
	public void setSeId(int seId) {
		this.seId = seId;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + deId;
		result = prime * result + seId;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DeviceServiceId other = (DeviceServiceId) obj;
		if (deId != other.deId)
			return false;
		if (seId != other.seId)
			return false;
		return true;
	}

}
