/*             
 * 			  (                       
 *			 ( )\         (        (   
 *			 )((_)  (    ))\ (    ))\  
 *			((_)_   )\  /((_))\  /((_) 
 *			 | _ ) ((_)(_)) ((_)(_))   
 *			 | _ \/ _ \/ -_)(_-</ -_)  
 *			 |___/\___/\___|/__/\___|
 *       
 *           			;            
 *		      +        ;;;         + 
 *			  +       ;;;;;        + 
 *			  +      ;;;;;;;       + 
 *			  ++    ;;;;;;;;;     ++ 
 *			  +++++;;;;;;;;;;;+++++  
 *			   ++++;;;;;;;;;;;+++++  
 *				++;;;;;;;;;;;;;++    
 *			     ;;;;;;;;;;;;;;;     
 *			    ;;;;;;;;;;;;;;;;;     
 *				:::::::::::::::::    
 * 				:::::::::::::::::      
 *  			:::::::::::::::::    
 *   			::::::@@@@@::::::    
 *				:::::@:::::@:::::    
 *				::::@:::::::@::::    
 * 				:::::::::::::::::    
 *  			:::::::::::::::::      
 */



package de.bo.aid.boese.modelJPA;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Transient;

// TODO: Auto-generated Javadoc
/**
 * DeviceComponenteReplaceId Model for Hibernate generated by hbm2java.
 */
@Embeddable
public class DeviceComponentReplaceId implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	@Transient
	private static final long serialVersionUID = 1L;

	/** The DeviceComponent id. */
	@Column(name = "deCoId", nullable = false)
	private int deCoId;
	
	/** The DeviceComponent idreplaced. */
	@Column(name = "deCoIdreplaced", nullable = false)
	private int deCoIdreplaced;

	/**
	 * Instantiates a new device componente replace id.
	 */
	public DeviceComponentReplaceId() {
	}

	/**
	 * Instantiates a new device componente replace id.
	 *
	 * @param deCoId the DeviceComponent id
	 * @param deCoIdreplaced the DeviceComponent idreplaced
	 */
	public DeviceComponentReplaceId(int deCoId, int deCoIdreplaced) {
		this.deCoId = deCoId;
		this.deCoIdreplaced = deCoIdreplaced;
	}

	/**
	 * Gets the DeviceComponent id.
	 *
	 * @return the DeviceComponent id
	 */
	public int getDeCoId() {
		return this.deCoId;
	}

	/**
	 * Sets the DeviceComponent id.
	 *
	 * @param deCoId the new DeviceComponent id
	 */
	public void setDeCoId(int deCoId) {
		this.deCoId = deCoId;
	}

	/**
	 * Gets the DeviceComponent idreplaced.
	 *
	 * @return the DeviceComponent idreplaced
	 */
	public int getDeCoIdreplaced() {
		return this.deCoIdreplaced;
	}

	/**
	 * Sets the DeviceComponent idreplaced.
	 *
	 * @param deCoIdreplaced the new DeviceComponent idreplaced
	 */
	public void setDeCoIdreplaced(int deCoIdreplaced) {
		this.deCoIdreplaced = deCoIdreplaced;
	}

	/**
	 *  
	 * To compare two DeviceComponentReplaceIds.
	 *
	 * @param other the DeviceComponentReplaceId object to compare
	 * @return true if both DeviceComponentReplaceIds are equal
	 */
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DeviceComponentReplaceId))
			return false;
		DeviceComponentReplaceId castOther = (DeviceComponentReplaceId) other;

		return (this.getDeCoId() == castOther.getDeCoId())
				&& (this.getDeCoIdreplaced() == castOther.getDeCoIdreplaced());
	}

	/**
	 *  
	 * To create the hashCode.
	 *
	 * @return the hashCode
	 */
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDeCoId();
		result = 37 * result + this.getDeCoIdreplaced();
		return result;
	}

}
