/*             
 * 			  (                       
 *			 ( )\         (        (   
 *			 )((_)  (    ))\ (    ))\  
 *			((_)_   )\  /((_))\  /((_) 
 *			 | _ ) ((_)(_)) ((_)(_))   
 *			 | _ \/ _ \/ -_)(_-</ -_)  
 *			 |___/\___/\___|/__/\___|
 *       
 *           			;            
 *		      +        ;;;         + 
 *			  +       ;;;;;        + 
 *			  +      ;;;;;;;       + 
 *			  ++    ;;;;;;;;;     ++ 
 *			  +++++;;;;;;;;;;;+++++  
 *			   ++++;;;;;;;;;;;+++++  
 *				++;;;;;;;;;;;;;++    
 *			     ;;;;;;;;;;;;;;;     
 *			    ;;;;;;;;;;;;;;;;;     
 *				:::::::::::::::::    
 * 				:::::::::::::::::      
 *  			:::::::::::::::::    
 *   			::::::@@@@@::::::    
 *				:::::@:::::@:::::    
 *				::::@:::::::@::::    
 * 				:::::::::::::::::    
 *  			:::::::::::::::::      
 */



package de.bo.aid.boese.modelJPA;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Transient;

// TODO: Auto-generated Javadoc
/**
 * DeviceComponenteReplace Model for Hibernate generated by hbm2java.
 */
public class DeviceComponentReplace implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	@Transient
	private static final long serialVersionUID = 1L;

	/** The DeviceComponenteReplace id. */
	@EmbeddedId
	private DeviceComponentReplaceId id;
	
	/** The new DeviceComponent. */
	@ManyToOne(cascade = {CascadeType.ALL}, fetch = FetchType.LAZY)
	@JoinColumn(name = "deviceComponentByDeCoId", nullable = false)
	private DeviceComponent deviceComponentByDeCoId;
	
	/** The replaced DeviceComponent. */
	@ManyToOne(cascade = {CascadeType.ALL}, fetch = FetchType.LAZY)
	@JoinColumn(name = "deviceComponentByDeCoIdreplaced", nullable = false)
	private DeviceComponent deviceComponentByDeCoIdreplaced;
	
	/** The timestamp when it was replaced. */
	@Column(nullable = false)
	private Date timestamp;

	/**
	 * Instantiates a new deviceComponenteReplace.
	 */
	public DeviceComponentReplace() {
	}

	/**
	 * Instantiates a new deviceComponenteReplace for DB insert.
	 *
	 * @param deviceComponentByDeCoId the new DeviceComponent
	 * @param deviceComponentByDeCoIdreplaced replaced DeviceComponent
	 */
	public DeviceComponentReplace(DeviceComponent deviceComponentByDeCoId, DeviceComponent deviceComponentByDeCoIdreplaced) {
		this.deviceComponentByDeCoId = deviceComponentByDeCoId;
		this.deviceComponentByDeCoIdreplaced = deviceComponentByDeCoIdreplaced;
		this.timestamp = new Date();
	}

	/**
	 * Instantiates a new deviceComponenteReplace.
	 *
	 * @param id the DeviceComponenteReplaceId
	 * @param deviceComponentByDeCoId the new DeviceComponent
	 * @param deviceComponentByDeCoIdreplaced replaced DeviceComponent
	 * @param timestamp the timestamp when it was replaces
	 */
	public DeviceComponentReplace(DeviceComponentReplaceId id, DeviceComponent deviceComponentByDeCoId,
			DeviceComponent deviceComponentByDeCoIdreplaced, Date timestamp) {
		this.id = id;
		this.deviceComponentByDeCoId = deviceComponentByDeCoId;
		this.deviceComponentByDeCoIdreplaced = deviceComponentByDeCoIdreplaced;
		this.timestamp = timestamp;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	public DeviceComponentReplaceId getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(DeviceComponentReplaceId id) {
		this.id = id;
	}

	/**
	 * Gets the new DeviceComponent.
	 *
	 * @return the new DeviceComponent
	 */
	public DeviceComponent getDeviceComponentByDeCoId() {
		return this.deviceComponentByDeCoId;
	}

	/**
	 * Sets the new DeviceComponent.
	 *
	 * @param deviceComponentByDeCoId the new new DeviceComponent
	 */
	public void setDeviceComponentByDeCoId(DeviceComponent deviceComponentByDeCoId) {
		this.deviceComponentByDeCoId = deviceComponentByDeCoId;
	}

	/**
	 * Gets the replaced DeviceComponent.
	 *
	 * @return the replaced DeviceComponent
	 */
	public DeviceComponent getDeviceComponentByDeCoIdreplaced() {
		return this.deviceComponentByDeCoIdreplaced;
	}

	/**
	 * Sets the replaced DeviceComponent.
	 *
	 * @param deviceComponentByDeCoIdreplaced the replaced DeviceComponent
	 */
	public void setDeviceComponentByDeCoIdreplaced(DeviceComponent deviceComponentByDeCoIdreplaced) {
		this.deviceComponentByDeCoIdreplaced = deviceComponentByDeCoIdreplaced;
	}

	/**
	 * Gets the timestamp when it was replaces.
	 *
	 * @return the timestamp when it was replaces
	 */
	public Date getTimestamp() {
		return this.timestamp;
	}

	/**
	 * Sets the timestamp when it was replaces.
	 *
	 * @param timestamp the new timestamp when it was replaces
	 */
	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	/**
	 *  
	 * To compare two DeviceComponenteReplaces.
	 *
	 * @param obj the DeviceComponenteReplace object to compare
	 * @return true if both DeviceComponenteReplaces are equal
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DeviceComponentReplace other = (DeviceComponentReplace) obj;
		if (deviceComponentByDeCoId == null) {
			if (other.deviceComponentByDeCoId != null)
				return false;
		} else if (!deviceComponentByDeCoId.equals(other.deviceComponentByDeCoId))
			return false;
		if (deviceComponentByDeCoIdreplaced == null) {
			if (other.deviceComponentByDeCoIdreplaced != null)
				return false;
		} else if (!deviceComponentByDeCoIdreplaced.equals(other.deviceComponentByDeCoIdreplaced))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (timestamp == null) {
			if (other.timestamp != null)
				return false;
		} else if (!timestamp.equals(other.timestamp))
			return false;
		return true;
	}

}
