/*             
 * 			  (                       
 *			 ( )\         (        (   
 *			 )((_)  (    ))\ (    ))\  
 *			((_)_   )\  /((_))\  /((_) 
 *			 | _ ) ((_)(_)) ((_)(_))   
 *			 | _ \/ _ \/ -_)(_-</ -_)  
 *			 |___/\___/\___|/__/\___|
 *       
 *           			;            
 *		      +        ;;;         + 
 *			  +       ;;;;;        + 
 *			  +      ;;;;;;;       + 
 *			  ++    ;;;;;;;;;     ++ 
 *			  +++++;;;;;;;;;;;+++++  
 *			   ++++;;;;;;;;;;;+++++  
 *				++;;;;;;;;;;;;;++    
 *			     ;;;;;;;;;;;;;;;     
 *			    ;;;;;;;;;;;;;;;;;     
 *				:::::::::::::::::    
 * 				:::::::::::::::::      
 *  			:::::::::::::::::    
 *   			::::::@@@@@::::::    
 *				:::::@:::::@:::::    
 *				::::@:::::::@::::    
 * 				:::::::::::::::::    
 *  			:::::::::::::::::      
 */



package de.bo.aid.boese.modelJPA;

import java.util.Date;

// TODO: Auto-generated Javadoc
/**
 * DeviceComponenteReplace Model for Hibernate generated by hbm2java.
 */
public class DeviceComponenteReplace implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The DeviceComponenteReplace id. */
	private DeviceComponenteReplaceId id;
	
	/** The new DeviceComponent. */
	private DeviceComponent deviceComponentByDeCoId;
	
	/** The replaced DeviceComponent. */
	private DeviceComponent deviceComponentByDeCoIdreplaced;
	
	/** The timestap when it was replaced. */
	private Date timestap;

	/**
	 * Instantiates a new deviceComponenteReplace.
	 */
	public DeviceComponenteReplace() {
	}

	/**
	 * Instantiates a new deviceComponenteReplace.
	 *
	 * @param id the DeviceComponenteReplaceId
	 * @param deviceComponentByDeCoId the new DeviceComponent
	 * @param deviceComponentByDeCoIdreplaced replaced DeviceComponent
	 * @param timestap the timestap when it was replaces
	 */
	public DeviceComponenteReplace(DeviceComponenteReplaceId id, DeviceComponent deviceComponentByDeCoId,
			DeviceComponent deviceComponentByDeCoIdreplaced, Date timestap) {
		this.id = id;
		this.deviceComponentByDeCoId = deviceComponentByDeCoId;
		this.deviceComponentByDeCoIdreplaced = deviceComponentByDeCoIdreplaced;
		this.timestap = timestap;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	public DeviceComponenteReplaceId getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(DeviceComponenteReplaceId id) {
		this.id = id;
	}

	/**
	 * Gets the new DeviceComponent.
	 *
	 * @return the new DeviceComponent
	 */
	public DeviceComponent getDeviceComponentByDeCoId() {
		return this.deviceComponentByDeCoId;
	}

	/**
	 * Sets the new DeviceComponent.
	 *
	 * @param deviceComponentByDeCoId the new new DeviceComponent
	 */
	public void setDeviceComponentByDeCoId(DeviceComponent deviceComponentByDeCoId) {
		this.deviceComponentByDeCoId = deviceComponentByDeCoId;
	}

	/**
	 * Gets the replaced DeviceComponent.
	 *
	 * @return the replaced DeviceComponent
	 */
	public DeviceComponent getDeviceComponentByDeCoIdreplaced() {
		return this.deviceComponentByDeCoIdreplaced;
	}

	/**
	 * Sets the replaced DeviceComponent.
	 *
	 * @param deviceComponentByDeCoIdreplaced the replaced DeviceComponent
	 */
	public void setDeviceComponentByDeCoIdreplaced(DeviceComponent deviceComponentByDeCoIdreplaced) {
		this.deviceComponentByDeCoIdreplaced = deviceComponentByDeCoIdreplaced;
	}

	/**
	 * Gets the timestap when it was replaces.
	 *
	 * @return the timestap when it was replaces
	 */
	public Date getTimestap() {
		return this.timestap;
	}

	/**
	 * Sets the timestap when it was replaces.
	 *
	 * @param timestap the new timestap when it was replaces
	 */
	public void setTimestap(Date timestap) {
		this.timestap = timestap;
	}

	/**
	 *  
	 * To compare two DeviceComponenteReplaces.
	 *
	 * @param obj the DeviceComponenteReplace object to compare
	 * @return true if both DeviceComponenteReplaces are equal
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DeviceComponenteReplace other = (DeviceComponenteReplace) obj;
		if (deviceComponentByDeCoId == null) {
			if (other.deviceComponentByDeCoId != null)
				return false;
		} else if (!deviceComponentByDeCoId.equals(other.deviceComponentByDeCoId))
			return false;
		if (deviceComponentByDeCoIdreplaced == null) {
			if (other.deviceComponentByDeCoIdreplaced != null)
				return false;
		} else if (!deviceComponentByDeCoIdreplaced.equals(other.deviceComponentByDeCoIdreplaced))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (timestap == null) {
			if (other.timestap != null)
				return false;
		} else if (!timestap.equals(other.timestap))
			return false;
		return true;
	}

}
