/*             
 * 			  (                       
 *			 ( )\         (        (   
 *			 )((_)  (    ))\ (    ))\  
 *			((_)_   )\  /((_))\  /((_) 
 *			 | _ ) ((_)(_)) ((_)(_))   
 *			 | _ \/ _ \/ -_)(_-</ -_)  
 *			 |___/\___/\___|/__/\___|
 *       
 *           			;            
 *		      +        ;;;         + 
 *			  +       ;;;;;        + 
 *			  +      ;;;;;;;       + 
 *			  ++    ;;;;;;;;;     ++ 
 *			  +++++;;;;;;;;;;;+++++  
 *			   ++++;;;;;;;;;;;+++++  
 *				++;;;;;;;;;;;;;++    
 *			     ;;;;;;;;;;;;;;;     
 *			    ;;;;;;;;;;;;;;;;;     
 *				:::::::::::::::::    
 * 				:::::::::::::::::      
 *  			:::::::::::::::::    
 *   			::::::@@@@@::::::    
 *				:::::@:::::@:::::    
 *				::::@:::::::@::::    
 * 				:::::::::::::::::    
 *  			:::::::::::::::::      
 */



package de.bo.aid.boese.modelJPA;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

// TODO: Auto-generated Javadoc
/**
 * DeviceGroup Model for Hibernate generated by hbm2java.
 */
@Entity
@Table(name="\"DeviceGroup\"")
public class DeviceGroup implements java.io.Serializable, JPAModel {

	/** The Constant serialVersionUID. */
	@Transient
	private static final long serialVersionUID = 1L;

	/** The DeviceGroup id. */
	@Id
	@GeneratedValue(strategy=GenerationType.TABLE)
	private int id;
	
	/** The linked device. */
	@ManyToOne(cascade = {CascadeType.ALL}, fetch = FetchType.LAZY)
	@JoinColumn(name = "device", nullable = false)
	private Device device;
	
	/** The linked group. */
	@ManyToOne(cascade = {CascadeType.ALL}, fetch = FetchType.LAZY)
	@JoinColumn(name = "grp", nullable = false)
	private Group grp;
	
	/** The rights of the Group on this Device. */
	@Column(nullable = false)
	private short rights;

	/**
	 * Instantiates a new device group.
	 */
	public DeviceGroup() {
		
	}

	/**
	 * Instantiates a new device group for DB Insert.
	 *
	 * @param rights the rights of the Group on this Device
	 */
	public DeviceGroup(short rights) {
		this.rights = rights;
	}

	/**
	 * Instantiates a new device group.
	 *
	 * @param device the device
	 * @param grp the group
	 * @param rights the rights of the Group on this Device
	 */
	public DeviceGroup(Device device, Group grp, short rights) {
		this.device = device;
		this.grp = grp;
		this.rights = rights;
	}

	/**
	 * Instantiates a new device group.
	 *
	 * @param id the id
	 * @param device the device
	 * @param grp the group
	 * @param rights the rights of the Group on this Device
	 */
	public DeviceGroup(int id, Device device, Group grp, short rights) {
		this.id = id;
		this.device = device;
		this.grp = grp;
		this.rights = rights;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	public int getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Gets the device.
	 *
	 * @return the device
	 */
	public Device getDevice() {
		return this.device;
	}

	/**
	 * Sets the device.
	 *
	 * @param device the new device
	 */
	public void setDevice(Device device) {
		this.device = device;
	}

	/**
	 * Gets the group.
	 *
	 * @return the group
	 */
	public Group getGrp() {
		return this.grp;
	}

	/**
	 * Sets the group.
	 *
	 * @param grp the new group
	 */
	public void setGrp(Group grp) {
		this.grp = grp;
	}

	/**
	 * Gets the rights of the Group on this Device.
	 *
	 * @return the rights of the Group on this Device
	 */
	public short getRights() {
		return this.rights;
	}

	/**
	 * Sets the rights of the Group on this Device.
	 *
	 * @param rights the new rights of the Group on this Device
	 */
	public void setRights(short rights) {
		this.rights = rights;
	}

	/**
	 *  
	 * To compare two DeviceGroupIds.
	 *
	 * @param obj the DeviceGroupId object to compare
	 * @return true if both DeviceGroupIds are equal
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DeviceGroup other = (DeviceGroup) obj;
		if (id != other.id)
			return false;
		return true;
	}

	@Override
	public boolean equalsWithoutIDAndFK(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DeviceGroup other = (DeviceGroup) obj;
		if (device == null) {
			if (other.device != null)
				return false;
		} else if (!device.equals(other.device))
			return false;
		if (grp == null) {
			if (other.grp != null)
				return false;
		} else if (!grp.equals(other.grp))
			return false;
		if (rights != other.rights)
			return false;
		return true;
	}

}
