/*             
 * 			  (                       
 *			 ( )\         (        (   
 *			 )((_)  (    ))\ (    ))\  
 *			((_)_   )\  /((_))\  /((_) 
 *			 | _ ) ((_)(_)) ((_)(_))   
 *			 | _ \/ _ \/ -_)(_-</ -_)  
 *			 |___/\___/\___|/__/\___|
 *       
 *           			;            
 *		      +        ;;;         + 
 *			  +       ;;;;;        + 
 *			  +      ;;;;;;;       + 
 *			  ++    ;;;;;;;;;     ++ 
 *			  +++++;;;;;;;;;;;+++++  
 *			   ++++;;;;;;;;;;;+++++  
 *				++;;;;;;;;;;;;;++    
 *			     ;;;;;;;;;;;;;;;     
 *			    ;;;;;;;;;;;;;;;;;     
 *				:::::::::::::::::    
 * 				:::::::::::::::::      
 *  			:::::::::::::::::    
 *   			::::::@@@@@::::::    
 *				:::::@:::::@:::::    
 *				::::@:::::::@::::    
 * 				:::::::::::::::::    
 *  			:::::::::::::::::      
 */



package de.bo.aid.boese.modelJPA;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

// TODO: Auto-generated Javadoc
/**
 * DeviceComponenteReplace Model for Hibernate generated by hbm2java.
 */
@Entity
@Table(name="\"DeviceComponentReplace\"")
public class DeviceComponentReplace implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	@Transient
	private static final long serialVersionUID = 1L;

	/** The DeviceComponenteReplace id. */
	@Id
	@GeneratedValue(strategy=GenerationType.TABLE)
	private int id;
	
	/** The new DeviceComponent. */
	@ManyToOne(cascade = {CascadeType.ALL}, fetch = FetchType.LAZY)
	@JoinColumn(name = "deviceComponent", nullable = false)
	private DeviceComponent deviceComponent;
	
	/** The replaced DeviceComponent. */
	@ManyToOne(cascade = {CascadeType.ALL}, fetch = FetchType.LAZY)
	@JoinColumn(name = "deviceComponentreplaced", nullable = false)
	private DeviceComponent deviceComponentreplaced;
	
	/** The timestamp when it was replaced. */
	@Column(nullable = false)
	private Date timestamp;

	/**
	 * Instantiates a new deviceComponenteReplace.
	 */
	public DeviceComponentReplace() {
	}

	/**
	 * Instantiates a new deviceComponenteReplace for DB insert.
	 *
	 * @param deviceComponent the new DeviceComponent
	 * @param deviceComponentreplaced replaced DeviceComponent
	 */
	public DeviceComponentReplace(DeviceComponent deviceComponent, DeviceComponent deviceComponentreplaced) {
		this.deviceComponent = deviceComponent;
		this.deviceComponentreplaced = deviceComponentreplaced;
		this.timestamp = new Date();
	}

	/**
	 * Instantiates a new deviceComponenteReplace.
	 *
	 * @param id the DeviceComponenteReplaceId
	 * @param deviceComponent the new DeviceComponent
	 * @param deviceComponentreplaced replaced DeviceComponent
	 * @param timestamp the timestamp when it was replaces
	 */
	public DeviceComponentReplace(int id, DeviceComponent deviceComponent,
			DeviceComponent deviceComponentreplaced, Date timestamp) {
		this.id = id;
		this.deviceComponent = deviceComponent;
		this.deviceComponentreplaced = deviceComponentreplaced;
		this.timestamp = timestamp;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	public int getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Gets the new DeviceComponent.
	 *
	 * @return the new DeviceComponent
	 */
	public DeviceComponent getDeviceComponent() {
		return this.deviceComponent;
	}

	/**
	 * Sets the new DeviceComponent.
	 *
	 * @param deviceComponent the new new DeviceComponent
	 */
	public void setDeviceComponent(DeviceComponent deviceComponent) {
		this.deviceComponent = deviceComponent;
	}

	/**
	 * Gets the replaced DeviceComponent.
	 *
	 * @return the replaced DeviceComponent
	 */
	public DeviceComponent getDeviceComponentreplaced() {
		return this.deviceComponentreplaced;
	}

	/**
	 * Sets the replaced DeviceComponent.
	 *
	 * @param deviceComponentreplaced the replaced DeviceComponent
	 */
	public void setDeviceComponentreplaced(DeviceComponent deviceComponentreplaced) {
		this.deviceComponentreplaced = deviceComponentreplaced;
	}

	/**
	 * Gets the timestamp when it was replaces.
	 *
	 * @return the timestamp when it was replaces
	 */
	public Date getTimestamp() {
		return this.timestamp;
	}

	/**
	 * Sets the timestamp when it was replaces.
	 *
	 * @param timestamp the new timestamp when it was replaces
	 */
	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	/**
	 *  
	 * To compare two DeviceComponenteReplaces.
	 *
	 * @param obj the DeviceComponenteReplace object to compare
	 * @return true if both DeviceComponenteReplaces are equal
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DeviceComponentReplace other = (DeviceComponentReplace) obj;
		if (deviceComponent == null) {
			if (other.deviceComponent != null)
				return false;
		} else if (!deviceComponent.equals(other.deviceComponent))
			return false;
		if (deviceComponentreplaced == null) {
			if (other.deviceComponentreplaced != null)
				return false;
		} else if (!deviceComponentreplaced.equals(other.deviceComponentreplaced))
			return false;
		if (id != other.id)
			return false;
		if (timestamp == null) {
			if (other.timestamp != null)
				return false;
		} else if (!timestamp.equals(other.timestamp))
			return false;
		return true;
	}

}
