/*             
 * 			  (                       
 *			 ( )\         (        (   
 *			 )((_)  (    ))\ (    ))\  
 *			((_)_   )\  /((_))\  /((_) 
 *			 | _ ) ((_)(_)) ((_)(_))   
 *			 | _ \/ _ \/ -_)(_-</ -_)  
 *			 |___/\___/\___|/__/\___|
 *       
 *           			;            
 *		      +        ;;;         + 
 *			  +       ;;;;;        + 
 *			  +      ;;;;;;;       + 
 *			  ++    ;;;;;;;;;     ++ 
 *			  +++++;;;;;;;;;;;+++++  
 *			   ++++;;;;;;;;;;;+++++  
 *				++;;;;;;;;;;;;;++    
 *			     ;;;;;;;;;;;;;;;     
 *			    ;;;;;;;;;;;;;;;;;     
 *				:::::::::::::::::    
 * 				:::::::::::::::::      
 *  			:::::::::::::::::    
 *   			::::::@@@@@::::::    
 *				:::::@:::::@:::::    
 *				::::@:::::::@::::    
 * 				:::::::::::::::::    
 *  			:::::::::::::::::      
 */



package de.bo.aid.boese.modelJPA;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

// TODO: Auto-generated Javadoc
/**
 * GroupUser Model for Hibernate generated by hbm2java.
 */
@Entity
@Table(name="\"GroupUser\"")
public class GroupUser implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	@Transient
	private static final long serialVersionUID = 1L;

	/** The GroupUser id. */
	@Id
	@GeneratedValue(strategy=GenerationType.TABLE)
	private int id;
	
	/** The linked Group. */
	@ManyToOne(cascade = {CascadeType.ALL}, fetch = FetchType.LAZY)
	@JoinColumn(name = "grp", nullable = false)
	private Group grp;
	
	/** The linked User. */
	@ManyToOne(cascade = {CascadeType.ALL}, fetch = FetchType.LAZY)
	@JoinColumn(name = "\"user\"", nullable = false)
	private User user;
	
	/** The position of the User in the Group. */
	private Short position;

	/**
	 * Instantiates a new group user.
	 */
	public GroupUser() {
	}

	/**
	 * Instantiates a new group user.
	 *
	 * @param id the GroupUser id
	 * @param grp the linked Group
	 * @param user the linked User
	 */
	public GroupUser(int id, Group grp, User user) {
		this.id = id;
		this.grp = grp;
		this.user = user;
	}

	/**
	 * Instantiates a new group user for DB Insert.
	 *
	 * @param grp the linked Group
	 * @param user the linked User
	 */
	public GroupUser(Group grp, User user, Short position) {
		this.grp = grp;
		this.user = user;
		this.position = position;
	}

	/**
	 * Instantiates a new group user.
	 *
	 * @param id the GroupUser id
	 * @param grp the linked Group
	 * @param user the linked User
	 * @param position the position of the User in the Group
	 */
	public GroupUser(int id, Group grp, User user, Short position) {
		this.id = id;
		this.grp = grp;
		this.user = user;
		this.position = position;
	}

	/**
	 * Gets the GroupUser id.
	 *
	 * @return the GroupUser id
	 */
	public int getId() {
		return this.id;
	}

	/**
	 * Sets the GroupUser id.
	 *
	 * @param id the new GroupUser id
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Gets the group.
	 *
	 * @return the group
	 */
	public Group getGrp() {
		return this.grp;
	}

	/**
	 * Sets the group.
	 *
	 * @param grp the new group
	 */
	public void setGrp(Group grp) {
		this.grp = grp;
	}

	/**
	 * Gets the user.
	 *
	 * @return the user
	 */
	public User getUser() {
		return this.user;
	}

	/**
	 * Sets the user.
	 *
	 * @param user the new user
	 */
	public void setUser(User user) {
		this.user = user;
	}

	/**
	 * Gets the position of the User in the Group.
	 *
	 * @return the position of the User in the Group
	 */
	public Short getPosition() {
		return this.position;
	}

	/**
	 * Sets the position of the User in the Group.
	 *
	 * @param position the new position of the User in the Group
	 */
	public void setPosition(Short position) {
		this.position = position;
	}



	/**
	 *  
	 * To compare two GroupUsers.
	 *
	 * @param obj the GroupUser object to compare
	 * @return true if both GroupUsers are equal
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		GroupUser other = (GroupUser) obj;
		if (grp == null) {
			if (other.grp != null)
				return false;
		} else if (!grp.equals(other.grp))
			return false;
		if (id != other.id) {
			return false;
		}
		if (position == null) {
			if (other.position != null)
				return false;
		} else if (!position.equals(other.position))
			return false;
		if (user == null) {
			if (other.user != null)
				return false;
		} else if (!user.equals(other.user))
			return false;
		return true;
	}

}
