/*             
 * 			  (                       
 *			 ( )\         (        (   
 *			 )((_)  (    ))\ (    ))\  
 *			((_)_   )\  /((_))\  /((_) 
 *			 | _ ) ((_)(_)) ((_)(_))   
 *			 | _ \/ _ \/ -_)(_-</ -_)  
 *			 |___/\___/\___|/__/\___|
 *       
 *           			;            
 *		      +        ;;;         + 
 *			  +       ;;;;;        + 
 *			  +      ;;;;;;;       + 
 *			  ++    ;;;;;;;;;     ++ 
 *			  +++++;;;;;;;;;;;+++++  
 *			   ++++;;;;;;;;;;;+++++  
 *				++;;;;;;;;;;;;;++    
 *			     ;;;;;;;;;;;;;;;     
 *			    ;;;;;;;;;;;;;;;;;     
 *				:::::::::::::::::    
 * 				:::::::::::::::::      
 *  			:::::::::::::::::    
 *   			::::::@@@@@::::::    
 *				:::::@:::::@:::::    
 *				::::@:::::::@::::    
 * 				:::::::::::::::::    
 *  			:::::::::::::::::      
 */



package de.bo.aid.boese.modelJPA;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

// TODO: Auto-generated Javadoc
/**
 * HistoryLogDeviceComponent Model for Hibernate generated by hbm2java.
 */
@Entity
@Table(name="\"HistoryLogDeviceComponent\"")
public class HistoryLogDeviceComponent implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	@Transient
	private static final long serialVersionUID = 1L;

	/** The HistoryLogDeviceComponent id. */
	@Id
	@GeneratedValue(strategy=GenerationType.TABLE)
	private int hiLoCoId;
	
	/** The timestamp when it was switched. */
	@Column(nullable = false)
	private Date timestamp;
	
	/** The device component which is locked. */
	@ManyToOne(cascade = {CascadeType.ALL}, fetch = FetchType.LAZY)
	@JoinColumn(name = "deviceComponent", nullable = false)
	private DeviceComponent deviceComponent;
	
	/** The value which was executed. */
	@Column(precision = 25, scale = 10)
	private BigDecimal value;

	/**
	 * Instantiates a new history log device component.
	 */
	public HistoryLogDeviceComponent() {
	}

	/**
	 * Instantiates a new history log device component for DB insert.
	 *
	 * @param deviceComponent the deviceComponent which is locked
	 * @param value the value which was executed
	 * @param timestamp the time
	 */
	public HistoryLogDeviceComponent(DeviceComponent deviceComponent, BigDecimal value, Date timestamp) {
		this.deviceComponent = deviceComponent;
		this.value = value;
		this.timestamp = timestamp;
	}

	/**
	 * Gets the HistoryLogDeviceComponent id.
	 *
	 * @return the HistoryLogDeviceComponent id
	 */
	public int getHiLoCoId() {
		return this.hiLoCoId;
	}

	/**
	 * Sets the HistoryLogDeviceComponent id.
	 *
	 * @param hiLoCoId the new HistoryLogDeviceComponent id
	 */
	public void setHiLoCoId(int hiLoCoId) {
		this.hiLoCoId = hiLoCoId;
	}

	/**
	 * Gets the timestamp when it was switched.
	 *
	 * @return the timestamp when it was switched
	 */
	public Date getTimestamp() {
		return this.timestamp;
	}

	/**
	 * Sets the timestamp when it was switched.
	 *
	 * @param timestamp the new timestamp when it was switched
	 */
	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	/**
	 * Gets the DeviceComponent which is locked.
	 *
	 * @return the Device Component which is locked
	 */
	public DeviceComponent getDeviceComponent() {
		return this.deviceComponent;
	}

	/**
	 * Sets the DeviceComponent which is locked.
	 *
	 * @param deviceComponent the new CeviceComponent which is locked
	 */
	public void setDeviceComponent(DeviceComponent deviceComponent) {
		this.deviceComponent = deviceComponent;
	}

	/**
	 * Gets the value which was executed.
	 *
	 * @return the value which was executed
	 */
	public BigDecimal getValue() {
		return this.value;
	}

	/**
	 * Sets the value which was executed.
	 *
	 * @param value the new value which was executed
	 */
	public void setValue(BigDecimal value) {
		this.value = value;
	}

	/**
	 *  
	 * To compare two HistoryLogDeviceComponent.
	 *
	 * @param obj the HistoryLogDeviceComponent object to compare
	 * @return true if both HistoryLogDeviceComponent are equal
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		HistoryLogDeviceComponent other = (HistoryLogDeviceComponent) obj;
		if (deviceComponent == null) {
			if (other.deviceComponent != null)
				return false;
		} else if (!deviceComponent.equals(other.deviceComponent))
			return false;
		if (hiLoCoId != other.hiLoCoId)
			return false;
		if (timestamp == null) {
			if (other.timestamp != null)
				return false;
		} else if (!timestamp.equals(other.timestamp))
			return false;
		if (value == null) {
			if (other.value != null)
				return false;
		} else if (!value.equals(other.value))
			return false;
		return true;
	}
}