/*             
 * 			  (                       
 *			 ( )\         (        (   
 *			 )((_)  (    ))\ (    ))\  
 *			((_)_   )\  /((_))\  /((_) 
 *			 | _ ) ((_)(_)) ((_)(_))   
 *			 | _ \/ _ \/ -_)(_-</ -_)  
 *			 |___/\___/\___|/__/\___|
 *       
 *           			;            
 *		      +        ;;;         + 
 *			  +       ;;;;;        + 
 *			  +      ;;;;;;;       + 
 *			  ++    ;;;;;;;;;     ++ 
 *			  +++++;;;;;;;;;;;+++++  
 *			   ++++;;;;;;;;;;;+++++  
 *				++;;;;;;;;;;;;;++    
 *			     ;;;;;;;;;;;;;;;     
 *			    ;;;;;;;;;;;;;;;;;     
 *				:::::::::::::::::    
 * 				:::::::::::::::::      
 *  			:::::::::::::::::    
 *   			::::::@@@@@::::::    
 *				:::::@:::::@:::::    
 *				::::@:::::::@::::    
 * 				:::::::::::::::::    
 *  			:::::::::::::::::      
 */



package de.bo.aid.boese.modelJPA;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

// TODO: Auto-generated Javadoc
/**
 * Service Model for Hibernate generated by hbm2java.
 */
@Entity
@Table(name="\"Service\"")
public class Service implements java.io.Serializable, JPAModel {

	/** The Constant serialVersionUID. */
	@Transient
	private static final long serialVersionUID = 1L;

	/** The Service id. */
	@Id
	@GeneratedValue(strategy=GenerationType.TABLE)
	private int seId;
	
	/** The description. */
	@Column(nullable = false)
	private String description;
	
	
	/** The Devices which offer this Service. */
	@OneToMany(cascade = {CascadeType.ALL}, fetch = FetchType.LAZY, mappedBy = "service")
	private Set<DeviceService> deviceServices = new HashSet<DeviceService>(0);

	/**
	 * Instantiates a new service.
	 */
	public Service() {
		
	}

	/**
	 * Instantiates a new service for DB-Insert.
	 *
	 * @param description the description
	 */
	public Service(String description) {
		this.description = description;
	}

	/**
	 * Instantiates a new service with all parameters.
	 *
	 * @param seId the Service id
	 * @param description the description
	 */
	public Service(int seId, String description) {
		this.seId = seId;
		this.description = description;
	}

	/**
	 * Instantiates a new service with all parameters and foreign keys.
	 *
	 * @param seId the Service id
	 * @param description the description
	 * @param deviceServices the devices
	 */
	public Service(int seId, String description, Set<DeviceService> deviceServices) {
		this.seId = seId;
		this.description = description;
		this.deviceServices = deviceServices;
	}

	/**
	 * Gets the Service id.
	 *
	 * @return the Service id
	 */
	public int getSeId() {
		return this.seId;
	}

	/**
	 * Sets the Service id.
	 *
	 * @param seId the new Service id
	 */
	public void setSeId(int seId) {
		this.seId = seId;
	}

	/**
	 * Gets the description.
	 *
	 * @return the description
	 */
	public String getDescription() {
		return this.description;
	}

	/**
	 * Sets the description.
	 *
	 * @param description the new description
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Gets the devices which offer this Service.
	 *
	 * @return the devices which offer this Service
	 */
	public Set<DeviceService> getDevices() {
		return this.deviceServices;
	}

	/**
	 * Sets the devices which offer this Service.
	 *
	 * @param deviceServices the new devices which offer this Service
	 */
	public void setDevices(Set<DeviceService> deviceServices) {
		this.deviceServices = deviceServices;
	}

	/**
	 *  
	 * To compare two Services.
	 *
	 * @param obj the Service object to compare
	 * @return true if both Services are equal
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Service other = (Service) obj;
		if (seId != other.seId)
			return false;
		return true;
	}

	/**
	 *  
	 * To compare two Services.
	 *
	 * @param obj the Service object to compare
	 * @return true if both Services are equal
	 */
	public boolean equalsWithoutIDAndFK(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Service other = (Service) obj;
		if (description == null) {
			if (other.description != null)
				return false;
		} else if (!description.equals(other.description))
			return false;
		return true;
	}

	public Set<DeviceService> getDeviceServices() {
		return deviceServices;
	}

	public void setDeviceServices(Set<DeviceService> deviceServices) {
		this.deviceServices = deviceServices;
	}

}
