/*             
 * 			  (                       
 *			 ( )\         (        (   
 *			 )((_)  (    ))\ (    ))\  
 *			((_)_   )\  /((_))\  /((_) 
 *			 | _ ) ((_)(_)) ((_)(_))   
 *			 | _ \/ _ \/ -_)(_-</ -_)  
 *			 |___/\___/\___|/__/\___|
 *       
 *           			;            
 *		      +        ;;;         + 
 *			  +       ;;;;;        + 
 *			  +      ;;;;;;;       + 
 *			  ++    ;;;;;;;;;     ++ 
 *			  +++++;;;;;;;;;;;+++++  
 *			   ++++;;;;;;;;;;;+++++  
 *				++;;;;;;;;;;;;;++    
 *			     ;;;;;;;;;;;;;;;     
 *			    ;;;;;;;;;;;;;;;;;     
 *				:::::::::::::::::    
 * 				:::::::::::::::::      
 *  			:::::::::::::::::    
 *   			::::::@@@@@::::::    
 *				:::::@:::::@:::::    
 *				::::@:::::::@::::    
 * 				:::::::::::::::::    
 *  			:::::::::::::::::      
 */



package de.bo.aid.boese.model;
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

// TODO: Auto-generated Javadoc
/**
 * Component generated by hbm2java.
 */
public class Component implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The co id. */
	private int coId;
	
	/** The unit. */
	private Unit unit;
	
	/** The name. */
	private String name;
	
	/** The sensor. */
	private boolean actor;
	
	/** The device components. */
	private Set<DeviceComponent> deviceComponents = new HashSet<DeviceComponent>(0);

	/**
	 * Instantiates a new component.
	 */
	public Component() {
	}

	/**
	 * Instantiates a new component.
	 *
	 * @param coId the co id
	 * @param unit the unit
	 * @param name the name
	 * @param sensor the sensor
	 */
	public Component(int coId, Unit unit, String name, boolean sensor) {
		this.coId = coId;
		this.unit = unit;
		this.name = name;
		this.actor = sensor;
	}

	/**
	 * Instantiates a new component.
	 *
	 * @param coId the co id
	 * @param unit the unit
	 * @param name the name
	 * @param sensor the sensor
	 * @param deviceComponents the device components
	 */
	public Component(int coId, Unit unit, String name, boolean sensor, Set<DeviceComponent> deviceComponents) {
		this.coId = coId;
		this.unit = unit;
		this.name = name;
		this.actor = sensor;
		this.deviceComponents = deviceComponents;
	}

	/**
	 * Gets the co id.
	 *
	 * @return the co id
	 */
	public int getCoId() {
		return this.coId;
	}

	/**
	 * Sets the co id.
	 *
	 * @param coId the new co id
	 */
	public void setCoId(int coId) {
		this.coId = coId;
	}

	/**
	 * Gets the unit.
	 *
	 * @return the unit
	 */
	public Unit getUnit() {
		return this.unit;
	}

	/**
	 * Sets the unit.
	 *
	 * @param unit the new unit
	 */
	public void setUnit(Unit unit) {
		this.unit = unit;
	}

	/**
	 * Gets the name.
	 *
	 * @return the name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Sets the name.
	 *
	 * @param name the new name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Checks if is sensor.
	 *
	 * @return true, if is sensor
	 */
	public boolean isActor() {
		return this.actor;
	}

	/**
	 * Sets the sensor.
	 *
	 * @param actor the new actor
	 */
	public void setActor(boolean actor) {
		this.actor = actor;
	}

	/**
	 * Gets the device components.
	 *
	 * @return the device components
	 */
	public Set<DeviceComponent> getDeviceComponents() {
		return this.deviceComponents;
	}

	/**
	 * Sets the device components.
	 *
	 * @param deviceComponents the new device components
	 */
	public void setDeviceComponents(Set<DeviceComponent> deviceComponents) {
		this.deviceComponents = deviceComponents;
	}

}
