package de.bo.aid.boese.model;
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Component generated by hbm2java
 */
public class Component implements java.io.Serializable {

	private int coId;
	private Unit unit;
	private String name;
	private boolean sensor;
	private Set deviceComponents = new HashSet(0);

	public Component() {
	}

	public Component(int coId, Unit unit, String name, boolean sensor) {
		this.coId = coId;
		this.unit = unit;
		this.name = name;
		this.sensor = sensor;
	}

	public Component(int coId, Unit unit, String name, boolean sensor, Set deviceComponents) {
		this.coId = coId;
		this.unit = unit;
		this.name = name;
		this.sensor = sensor;
		this.deviceComponents = deviceComponents;
	}

	public int getCoId() {
		return this.coId;
	}

	public void setCoId(int coId) {
		this.coId = coId;
	}

	public Unit getUnit() {
		return this.unit;
	}

	public void setUnit(Unit unit) {
		this.unit = unit;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isSensor() {
		return this.sensor;
	}

	public void setSensor(boolean sensor) {
		this.sensor = sensor;
	}

	public Set getDeviceComponents() {
		return this.deviceComponents;
	}

	public void setDeviceComponents(Set deviceComponents) {
		this.deviceComponents = deviceComponents;
	}

}
