package de.bo.aid.boese.model;

import java.util.HashSet;
import java.util.Set;

// TODO: Auto-generated Javadoc
/**
 * Connector generated by hbm2java.
 */
public class Connector implements java.io.Serializable {

	/** The co id. */
	private int coId;
	
	/** The name. */
	private String name;
	
	/** The password. */
	private String password;

	/** The status. */
	private short status;
	
	/** The history log connectors. */
	private Set historyLogConnectors = new HashSet(0);
	
	/** The devices. */
	private Set devices = new HashSet(0);
	
	/** The log connectors. */
	private Set logConnectors = new HashSet(0);

	/**
	 * Instantiates a new connector.
	 */
	public Connector() {
	
	}
	
	/**
	 * Instantiates a new connector.
	 *
	 * @param coId the co id
	 */
	public Connector(int coId) {
		this.coId = coId;
	}

	/**
	 * Instantiates a new connector.
	 *
	 * @param coId the connectorid
	 * @param name the name
	 * @param password the password
	 * @param status the status
	 */
	public Connector(int coId, String name, String password, short status) {
		this.coId = coId;
		this.name = name;
		this.password = password;
		this.status = status;
	}

	/**
	 * Instantiates a new connector.
	 *
	 * @param coId the co id
	 * @param name the name
	 * @param password the password
	 * @param historyLogConnectors the history log connectors
	 * @param devices the devices
	 * @param logConnectors the log connectors
	 */
	public Connector(int coId, String name, String password, short status,
			Set historyLogConnectors, Set devices, Set logConnectors) {
		this.coId = coId;
		this.name = name;
		this.password = password;
		this.status = status;
		this.historyLogConnectors = historyLogConnectors;
		this.devices = devices;
		this.logConnectors = logConnectors;
	}

	/**
	 * Gets the co id.
	 *
	 * @return the co id
	 */
	public int getCoId() {
		return this.coId;
	}

	/**
	 * Sets the co id.
	 *
	 * @param coId the new co id
	 */
	public void setCoId(int coId) {
		this.coId = coId;
	}

	/**
	 * Gets the name.
	 *
	 * @return the name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Sets the name.
	 *
	 * @param name the new name
	 */
	public void setName(String name) {
		this.name = name;
	}


	/**
	 * Gets the password.
	 *
	 * @return the password
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * Sets the password.
	 *
	 * @param password the new password
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	public short getStatus() {
		return status;
	}

	public void setStatus(short status) {
		this.status = status;
	}

	/**
	 * Gets the history log connectors.
	 *
	 * @return the history log connectors
	 */
	public Set getHistoryLogConnectors() {
		return this.historyLogConnectors;
	}

	/**
	 * Sets the history log connectors.
	 *
	 * @param historyLogConnectors the new history log connectors
	 */
	public void setHistoryLogConnectors(Set historyLogConnectors) {
		this.historyLogConnectors = historyLogConnectors;
	}

	/**
	 * Gets the devices.
	 *
	 * @return the devices
	 */
	public Set getDevices() {
		return this.devices;
	}

	/**
	 * Sets the devices.
	 *
	 * @param devices the new devices
	 */
	public void setDevices(Set devices) {
		this.devices = devices;
	}

	/**
	 * Gets the log connectors.
	 *
	 * @return the log connectors
	 */
	public Set getLogConnectors() {
		return this.logConnectors;
	}

	/**
	 * Sets the log connectors.
	 *
	 * @param logConnectors the new log connectors
	 */
	public void setLogConnectors(Set logConnectors) {
		this.logConnectors = logConnectors;
	}

}
