
package de.bo.aid.boese.model;
// TODO: Auto-generated Javadoc
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

/**
 * DeviceGroup generated by hbm2java.
 */
public class DeviceGroup implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	/** The id. */
	private DeviceGroupId id;
	
	/** The device. */
	private Device device;
	
	/** The group. */
	private Group group;
	
	/** The rights. */
	private short rights;

	/**
	 * Instantiates a new device group.
	 */
	public DeviceGroup() {
	}

	/**
	 * Instantiates a new device group.
	 *
	 * @param id the id
	 * @param device the device
	 * @param group the group
	 * @param rights the rights
	 */
	public DeviceGroup(DeviceGroupId id, Device device, Group group, short rights) {
		this.id = id;
		this.device = device;
		this.group = group;
		this.rights = rights;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	public DeviceGroupId getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(DeviceGroupId id) {
		this.id = id;
	}

	/**
	 * Gets the device.
	 *
	 * @return the device
	 */
	public Device getDevice() {
		return this.device;
	}

	/**
	 * Sets the device.
	 *
	 * @param device the new device
	 */
	public void setDevice(Device device) {
		this.device = device;
	}

	/**
	 * Gets the group.
	 *
	 * @return the group
	 */
	public Group getGroup() {
		return this.group;
	}

	/**
	 * Sets the group.
	 *
	 * @param group the new group
	 */
	public void setGroup(Group group) {
		this.group = group;
	}

	/**
	 * Gets the rights.
	 *
	 * @return the rights
	 */
	public short getRights() {
		return this.rights;
	}

	/**
	 * Sets the rights.
	 *
	 * @param rights the new rights
	 */
	public void setRights(short rights) {
		this.rights = rights;
	}

}
