/*             
 * 			  (                       
 *			 ( )\         (        (   
 *			 )((_)  (    ))\ (    ))\  
 *			((_)_   )\  /((_))\  /((_) 
 *			 | _ ) ((_)(_)) ((_)(_))   
 *			 | _ \/ _ \/ -_)(_-</ -_)  
 *			 |___/\___/\___|/__/\___|
 *       
 *           			;            
 *		      +        ;;;         + 
 *			  +       ;;;;;        + 
 *			  +      ;;;;;;;       + 
 *			  ++    ;;;;;;;;;     ++ 
 *			  +++++;;;;;;;;;;;+++++  
 *			   ++++;;;;;;;;;;;+++++  
 *				++;;;;;;;;;;;;;++    
 *			     ;;;;;;;;;;;;;;;     
 *			    ;;;;;;;;;;;;;;;;;     
 *				:::::::::::::::::    
 * 				:::::::::::::::::      
 *  			:::::::::::::::::    
 *   			::::::@@@@@::::::    
 *				:::::@:::::@:::::    
 *				::::@:::::::@::::    
 * 				:::::::::::::::::    
 *  			:::::::::::::::::      
 */



package de.bo.aid.boese.model;
// TODO: Auto-generated Javadoc
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

/**
 * DeviceComponenteReplaceId Model for Hibernate generated by hbm2java.
 */
public class DeviceComponenteReplaceId implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The de co id. */
	private int deCoId;
	
	/** The de co idreplaced. */
	private int deCoIdreplaced;

	/**
	 * Instantiates a new device componente replace id.
	 */
	public DeviceComponenteReplaceId() {
	}

	/**
	 * Instantiates a new device componente replace id.
	 *
	 * @param deCoId the de co id
	 * @param deCoIdreplaced the de co idreplaced
	 */
	public DeviceComponenteReplaceId(int deCoId, int deCoIdreplaced) {
		this.deCoId = deCoId;
		this.deCoIdreplaced = deCoIdreplaced;
	}

	/**
	 * Gets the de co id.
	 *
	 * @return the de co id
	 */
	public int getDeCoId() {
		return this.deCoId;
	}

	/**
	 * Sets the de co id.
	 *
	 * @param deCoId the new de co id
	 */
	public void setDeCoId(int deCoId) {
		this.deCoId = deCoId;
	}

	/**
	 * Gets the de co idreplaced.
	 *
	 * @return the de co idreplaced
	 */
	public int getDeCoIdreplaced() {
		return this.deCoIdreplaced;
	}

	/**
	 * Sets the de co idreplaced.
	 *
	 * @param deCoIdreplaced the new de co idreplaced
	 */
	public void setDeCoIdreplaced(int deCoIdreplaced) {
		this.deCoIdreplaced = deCoIdreplaced;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DeviceComponenteReplaceId))
			return false;
		DeviceComponenteReplaceId castOther = (DeviceComponenteReplaceId) other;

		return (this.getDeCoId() == castOther.getDeCoId())
				&& (this.getDeCoIdreplaced() == castOther.getDeCoIdreplaced());
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDeCoId();
		result = 37 * result + this.getDeCoIdreplaced();
		return result;
	}

}
