
package de.bo.aid.boese.model;
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

// TODO: Auto-generated Javadoc
/**
 * DeviceComponent generated by hbm2java.
 */
public class DeviceComponent implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	/** The de co id. */
	private int deCoId;
	
	/** The component. */
	private Component component;
	
	/** The device. */
	private Device device;
	
	/** The status. */
	private Short status;
	
	/** The description. */
	private String description;
	
	/** The log rule. */
	private BigDecimal logRule;
	
	/** The current value. */
	private BigDecimal currentValue;
	
	/** The device componente replaces for de co id. */
	private Set<DeviceComponenteReplace> deviceComponenteReplacesForDeCoId = new HashSet<DeviceComponenteReplace>(0);
	
	/** The history log device components. */
	private Set<HistoryLogDeviceComponent> historyLogDeviceComponents = new HashSet<HistoryLogDeviceComponent>(0);
	
	/** The device componente replaces for de co idreplaced. */
	private Set<DeviceComponenteReplace> deviceComponenteReplacesForDeCoIdreplaced = new HashSet<DeviceComponenteReplace>(0);
	
	/** The log device components. */
	private Set<LogDeviceComponent> logDeviceComponents = new HashSet<LogDeviceComponent>(0);
	
	/** The ToDos. */
	private Set<ToDo> toDos = new HashSet<ToDo>(0);

	/**
	 * Instantiates a new device component.
	 */
	public DeviceComponent() {
	
	}
	
	/**
	 * Instantiates a new device component.
	 *
	 * @param deCoId the de co id
	 */
	public DeviceComponent(int deCoId){
		this.deCoId = deCoId;
	}

	/**
	 * Instantiates a new device component.
	 *
	 * @param deCoId the de co id
	 * @param component the component
	 * @param device the device
	 */
	public DeviceComponent(int deCoId, Component component, Device device) {
		this.deCoId = deCoId;
		this.component = component;
		this.device = device;
	}

	/**
	 * Instantiates a new device component.
	 *
	 * @param deCoId the de co id
	 * @param component the component
	 * @param device the device
	 * @param status the status
	 * @param description the description
	 * @param logRule the log rule
	 * @param currentValue the current value
	 * @param deviceComponenteReplacesForDeCoId the device componente replaces for de co id
	 * @param historyLogDeviceComponents the history log device components
	 * @param deviceComponenteReplacesForDeCoIdreplaced the device componente replaces for de co idreplaced
	 * @param logDeviceComponents the log device components
	 */
	public DeviceComponent(int deCoId, Component component, Device device, Short status, String description,
			BigDecimal logRule, BigDecimal currentValue, Set<DeviceComponenteReplace> deviceComponenteReplacesForDeCoId,
			Set<HistoryLogDeviceComponent> historyLogDeviceComponents, Set<DeviceComponenteReplace> deviceComponenteReplacesForDeCoIdreplaced,
			Set<LogDeviceComponent> logDeviceComponents, Set<ToDo> toDos) {
		this.deCoId = deCoId;
		this.component = component;
		this.device = device;
		this.status = status;
		this.description = description;
		this.logRule = logRule;
		this.currentValue = currentValue;
		this.deviceComponenteReplacesForDeCoId = deviceComponenteReplacesForDeCoId;
		this.historyLogDeviceComponents = historyLogDeviceComponents;
		this.deviceComponenteReplacesForDeCoIdreplaced = deviceComponenteReplacesForDeCoIdreplaced;
		this.logDeviceComponents = logDeviceComponents;
		this.toDos = toDos;
	}

	/**
	 * Gets the de co id.
	 *
	 * @return the de co id
	 */
	public int getDeCoId() {
		return this.deCoId;
	}

	/**
	 * Sets the de co id.
	 *
	 * @param deCoId the new de co id
	 */
	public void setDeCoId(int deCoId) {
		this.deCoId = deCoId;
	}

	/**
	 * Gets the component.
	 *
	 * @return the component
	 */
	public Component getComponent() {
		return this.component;
	}

	/**
	 * Sets the component.
	 *
	 * @param component the new component
	 */
	public void setComponent(Component component) {
		this.component = component;
	}

	/**
	 * Gets the device.
	 *
	 * @return the device
	 */
	public Device getDevice() {
		return this.device;
	}

	/**
	 * Sets the device.
	 *
	 * @param device the new device
	 */
	public void setDevice(Device device) {
		this.device = device;
	}

	/**
	 * Gets the status.
	 *
	 * @return the status
	 */
	public Short getStatus() {
		return this.status;
	}

	/**
	 * Sets the status.
	 *
	 * @param status the new status
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * Gets the description.
	 *
	 * @return the description
	 */
	public String getDescription() {
		return this.description;
	}

	/**
	 * Sets the description.
	 *
	 * @param description the new description
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Gets the log rule.
	 *
	 * @return the log rule
	 */
	public BigDecimal getLogRule() {
		return this.logRule;
	}

	/**
	 * Sets the log rule.
	 *
	 * @param logRule the new log rule
	 */
	public void setLogRule(BigDecimal logRule) {
		this.logRule = logRule;
	}

	/**
	 * Gets the current value.
	 *
	 * @return the current value
	 */
	public BigDecimal getCurrentValue() {
		return this.currentValue;
	}

	/**
	 * Sets the current value.
	 *
	 * @param currentValue the new current value
	 */
	public void setCurrentValue(BigDecimal currentValue) {
		this.currentValue = currentValue;
	}

	/**
	 * Gets the device componente replaces for de co id.
	 *
	 * @return the device componente replaces for de co id
	 */
	public Set<DeviceComponenteReplace> getDeviceComponenteReplacesForDeCoId() {
		return this.deviceComponenteReplacesForDeCoId;
	}

	/**
	 * Sets the device componente replaces for de co id.
	 *
	 * @param deviceComponenteReplacesForDeCoId the new device componente replaces for de co id
	 */
	public void setDeviceComponenteReplacesForDeCoId(Set<DeviceComponenteReplace> deviceComponenteReplacesForDeCoId) {
		this.deviceComponenteReplacesForDeCoId = deviceComponenteReplacesForDeCoId;
	}

	/**
	 * Gets the history log device components.
	 *
	 * @return the history log device components
	 */
	public Set<HistoryLogDeviceComponent> getHistoryLogDeviceComponents() {
		return this.historyLogDeviceComponents;
	}

	/**
	 * Sets the history log device components.
	 *
	 * @param historyLogDeviceComponents the new history log device components
	 */
	public void setHistoryLogDeviceComponents(Set<HistoryLogDeviceComponent> historyLogDeviceComponents) {
		this.historyLogDeviceComponents = historyLogDeviceComponents;
	}

	/**
	 * Gets the device componente replaces for de co idreplaced.
	 *
	 * @return the device componente replaces for de co idreplaced
	 */
	public Set<DeviceComponenteReplace> getDeviceComponenteReplacesForDeCoIdreplaced() {
		return this.deviceComponenteReplacesForDeCoIdreplaced;
	}

	/**
	 * Sets the device componente replaces for de co idreplaced.
	 *
	 * @param deviceComponenteReplacesForDeCoIdreplaced the new device componente replaces for de co idreplaced
	 */
	public void setDeviceComponenteReplacesForDeCoIdreplaced(Set<DeviceComponenteReplace> deviceComponenteReplacesForDeCoIdreplaced) {
		this.deviceComponenteReplacesForDeCoIdreplaced = deviceComponenteReplacesForDeCoIdreplaced;
	}

	/**
	 * Gets the log device components.
	 *
	 * @return the log device components
	 */
	public Set<LogDeviceComponent> getLogDeviceComponents() {
		return this.logDeviceComponents;
	}

	/**
	 * Sets the log device components.
	 *
	 * @param logDeviceComponents the new log device components
	 */
	public void setLogDeviceComponents(Set<LogDeviceComponent> logDeviceComponents) {
		this.logDeviceComponents = logDeviceComponents;
	}

	public Set<ToDo> getToDos() {
		return toDos;
	}

	public void setToDos(Set<ToDo> toDos) {
		this.toDos = toDos;
	}

}
