/*             
 * 			  (                       
 *			 ( )\         (        (   
 *			 )((_)  (    ))\ (    ))\  
 *			((_)_   )\  /((_))\  /((_) 
 *			 | _ ) ((_)(_)) ((_)(_))   
 *			 | _ \/ _ \/ -_)(_-</ -_)  
 *			 |___/\___/\___|/__/\___|
 *       
 *           			;            
 *		      +        ;;;         + 
 *			  +       ;;;;;        + 
 *			  +      ;;;;;;;       + 
 *			  ++    ;;;;;;;;;     ++ 
 *			  +++++;;;;;;;;;;;+++++  
 *			   ++++;;;;;;;;;;;+++++  
 *				++;;;;;;;;;;;;;++    
 *			     ;;;;;;;;;;;;;;;     
 *			    ;;;;;;;;;;;;;;;;;     
 *				:::::::::::::::::    
 * 				:::::::::::::::::      
 *  			:::::::::::::::::    
 *   			::::::@@@@@::::::    
 *				:::::@:::::@:::::    
 *				::::@:::::::@::::    
 * 				:::::::::::::::::    
 *  			:::::::::::::::::      
 */



package de.bo.aid.boese.model;
// TODO: Auto-generated Javadoc
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

/**
 * DeviceGroupId generated by hbm2java.
 */
public class DeviceGroupId implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The de id. */
	private int deId;
	
	/** The gr id. */
	private short grId;

	/**
	 * Instantiates a new device group id.
	 */
	public DeviceGroupId() {
	}

	/**
	 * Instantiates a new device group id.
	 *
	 * @param deId the de id
	 * @param grId the gr id
	 */
	public DeviceGroupId(int deId, short grId) {
		this.deId = deId;
		this.grId = grId;
	}

	/**
	 * Gets the de id.
	 *
	 * @return the de id
	 */
	public int getDeId() {
		return this.deId;
	}

	/**
	 * Sets the de id.
	 *
	 * @param deId the new de id
	 */
	public void setDeId(int deId) {
		this.deId = deId;
	}

	/**
	 * Gets the gr id.
	 *
	 * @return the gr id
	 */
	public short getGrId() {
		return this.grId;
	}

	/**
	 * Sets the gr id.
	 *
	 * @param grId the new gr id
	 */
	public void setGrId(short grId) {
		this.grId = grId;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DeviceGroupId))
			return false;
		DeviceGroupId castOther = (DeviceGroupId) other;

		return (this.getDeId() == castOther.getDeId()) && (this.getGrId() == castOther.getGrId());
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDeId();
		result = 37 * result + this.getGrId();
		return result;
	}

}
