package de.bo.aid.boese.model;
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

/**
 * DeviceGroupId generated by hbm2java
 */
public class DeviceGroupId implements java.io.Serializable {

	private int deId;
	private short grId;

	public DeviceGroupId() {
	}

	public DeviceGroupId(int deId, short grId) {
		this.deId = deId;
		this.grId = grId;
	}

	public int getDeId() {
		return this.deId;
	}

	public void setDeId(int deId) {
		this.deId = deId;
	}

	public short getGrId() {
		return this.grId;
	}

	public void setGrId(short grId) {
		this.grId = grId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DeviceGroupId))
			return false;
		DeviceGroupId castOther = (DeviceGroupId) other;

		return (this.getDeId() == castOther.getDeId()) && (this.getGrId() == castOther.getGrId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDeId();
		result = 37 * result + this.getGrId();
		return result;
	}

}
