package de.bo.aid.boese.model;
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

/**
 * DeviceComponenteReplaceId generated by hbm2java
 */
public class DeviceComponenteReplaceId implements java.io.Serializable {

	private int deCoId;
	private int deCoIdreplaced;

	public DeviceComponenteReplaceId() {
	}

	public DeviceComponenteReplaceId(int deCoId, int deCoIdreplaced) {
		this.deCoId = deCoId;
		this.deCoIdreplaced = deCoIdreplaced;
	}

	public int getDeCoId() {
		return this.deCoId;
	}

	public void setDeCoId(int deCoId) {
		this.deCoId = deCoId;
	}

	public int getDeCoIdreplaced() {
		return this.deCoIdreplaced;
	}

	public void setDeCoIdreplaced(int deCoIdreplaced) {
		this.deCoIdreplaced = deCoIdreplaced;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DeviceComponenteReplaceId))
			return false;
		DeviceComponenteReplaceId castOther = (DeviceComponenteReplaceId) other;

		return (this.getDeCoId() == castOther.getDeCoId())
				&& (this.getDeCoIdreplaced() == castOther.getDeCoIdreplaced());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDeCoId();
		result = 37 * result + this.getDeCoIdreplaced();
		return result;
	}

}
