package de.bo.aid.boese.model;
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Device generated by hbm2java
 */
public class Device implements java.io.Serializable {

	private int deId;
	private Connector connector;
	private Zone zone;
	private String alias;
	private String serialNumber;
	private Date purchaseDate;
	private Set deviceGroups = new HashSet(0);
	private Set services = new HashSet(0);
	private Set deviceComponents = new HashSet(0);

	public Device() {
		
	}
	
	public Device(int deId) {
		this.deId = deId;
	}

	public Device(int deId, Connector connector, Zone zone, String alias, String serialNumber) {
		this.deId = deId;
		this.connector = connector;
		this.zone = zone;
		this.alias = alias;
		this.serialNumber = serialNumber;
	}

	public Device(int deId, Connector connector, Zone zone, String alias, String serialNumber, Date purchaseDate,
			Set deviceGroups, Set services, Set deviceComponents) {
		this.deId = deId;
		this.connector = connector;
		this.zone = zone;
		this.alias = alias;
		this.serialNumber = serialNumber;
		this.purchaseDate = purchaseDate;
		this.deviceGroups = deviceGroups;
		this.services = services;
		this.deviceComponents = deviceComponents;
	}

	public int getDeId() {
		return this.deId;
	}

	public void setDeId(int deId) {
		this.deId = deId;
	}

	public Connector getConnector() {
		return this.connector;
	}

	public void setConnector(Connector connector) {
		this.connector = connector;
	}

	public Zone getZone() {
		return this.zone;
	}

	public void setZone(Zone zone) {
		this.zone = zone;
	}

	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	public String getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	public Date getPurchaseDate() {
		return this.purchaseDate;
	}

	public void setPurchaseDate(Date purchaseDate) {
		this.purchaseDate = purchaseDate;
	}

	public Set getDeviceGroups() {
		return this.deviceGroups;
	}

	public void setDeviceGroups(Set deviceGroups) {
		this.deviceGroups = deviceGroups;
	}

	public Set getServices() {
		return this.services;
	}

	public void setServices(Set services) {
		this.services = services;
	}

	public Set getDeviceComponents() {
		return this.deviceComponents;
	}

	public void setDeviceComponents(Set deviceComponents) {
		this.deviceComponents = deviceComponents;
	}

}
