package de.bo.aid.boese.model;
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DeviceComponenteReplace generated by hbm2java
 */
public class DeviceComponenteReplace implements java.io.Serializable {

	private DeviceComponenteReplaceId id;
	private DeviceComponent deviceComponentByDeCoId;
	private DeviceComponent deviceComponentByDeCoIdreplaced;
	private Date timestap;

	public DeviceComponenteReplace() {
	}

	public DeviceComponenteReplace(DeviceComponenteReplaceId id, DeviceComponent deviceComponentByDeCoId,
			DeviceComponent deviceComponentByDeCoIdreplaced, Date timestap) {
		this.id = id;
		this.deviceComponentByDeCoId = deviceComponentByDeCoId;
		this.deviceComponentByDeCoIdreplaced = deviceComponentByDeCoIdreplaced;
		this.timestap = timestap;
	}

	public DeviceComponenteReplaceId getId() {
		return this.id;
	}

	public void setId(DeviceComponenteReplaceId id) {
		this.id = id;
	}

	public DeviceComponent getDeviceComponentByDeCoId() {
		return this.deviceComponentByDeCoId;
	}

	public void setDeviceComponentByDeCoId(DeviceComponent deviceComponentByDeCoId) {
		this.deviceComponentByDeCoId = deviceComponentByDeCoId;
	}

	public DeviceComponent getDeviceComponentByDeCoIdreplaced() {
		return this.deviceComponentByDeCoIdreplaced;
	}

	public void setDeviceComponentByDeCoIdreplaced(DeviceComponent deviceComponentByDeCoIdreplaced) {
		this.deviceComponentByDeCoIdreplaced = deviceComponentByDeCoIdreplaced;
	}

	public Date getTimestap() {
		return this.timestap;
	}

	public void setTimestap(Date timestap) {
		this.timestap = timestap;
	}

}
