package de.bo.aid.boese.model;
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * DeviceComponent generated by hbm2java
 */
public class DeviceComponent implements java.io.Serializable {

	private int deCoId;
	private Component component;
	private Device device;
	private Short status;
	private String description;
	private BigDecimal logRule;
	private BigDecimal currentValue;
	private Set deviceComponenteReplacesForDeCoId = new HashSet(0);
	private Set historyLogDeviceComponents = new HashSet(0);
	private Set deviceComponenteReplacesForDeCoIdreplaced = new HashSet(0);
	private Set logDeviceComponents = new HashSet(0);

	public DeviceComponent() {
	
	}
	
	public DeviceComponent(int deCoId){
		this.deCoId = deCoId;
	}

	public DeviceComponent(int deCoId, Component component, Device device) {
		this.deCoId = deCoId;
		this.component = component;
		this.device = device;
	}

	public DeviceComponent(int deCoId, Component component, Device device, Short status, String description,
			BigDecimal logRule, BigDecimal currentValue, Set deviceComponenteReplacesForDeCoId,
			Set historyLogDeviceComponents, Set deviceComponenteReplacesForDeCoIdreplaced, Set logDeviceComponents) {
		this.deCoId = deCoId;
		this.component = component;
		this.device = device;
		this.status = status;
		this.description = description;
		this.logRule = logRule;
		this.currentValue = currentValue;
		this.deviceComponenteReplacesForDeCoId = deviceComponenteReplacesForDeCoId;
		this.historyLogDeviceComponents = historyLogDeviceComponents;
		this.deviceComponenteReplacesForDeCoIdreplaced = deviceComponenteReplacesForDeCoIdreplaced;
		this.logDeviceComponents = logDeviceComponents;
	}

	public int getDeCoId() {
		return this.deCoId;
	}

	public void setDeCoId(int deCoId) {
		this.deCoId = deCoId;
	}

	public Component getComponent() {
		return this.component;
	}

	public void setComponent(Component component) {
		this.component = component;
	}

	public Device getDevice() {
		return this.device;
	}

	public void setDevice(Device device) {
		this.device = device;
	}

	public Short getStatus() {
		return this.status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public BigDecimal getLogRule() {
		return this.logRule;
	}

	public void setLogRule(BigDecimal logRule) {
		this.logRule = logRule;
	}

	public BigDecimal getCurrentValue() {
		return this.currentValue;
	}

	public void setCurrentValue(BigDecimal currentValue) {
		this.currentValue = currentValue;
	}

	public Set getDeviceComponenteReplacesForDeCoId() {
		return this.deviceComponenteReplacesForDeCoId;
	}

	public void setDeviceComponenteReplacesForDeCoId(Set deviceComponenteReplacesForDeCoId) {
		this.deviceComponenteReplacesForDeCoId = deviceComponenteReplacesForDeCoId;
	}

	public Set getHistoryLogDeviceComponents() {
		return this.historyLogDeviceComponents;
	}

	public void setHistoryLogDeviceComponents(Set historyLogDeviceComponents) {
		this.historyLogDeviceComponents = historyLogDeviceComponents;
	}

	public Set getDeviceComponenteReplacesForDeCoIdreplaced() {
		return this.deviceComponenteReplacesForDeCoIdreplaced;
	}

	public void setDeviceComponenteReplacesForDeCoIdreplaced(Set deviceComponenteReplacesForDeCoIdreplaced) {
		this.deviceComponenteReplacesForDeCoIdreplaced = deviceComponenteReplacesForDeCoIdreplaced;
	}

	public Set getLogDeviceComponents() {
		return this.logDeviceComponents;
	}

	public void setLogDeviceComponents(Set logDeviceComponents) {
		this.logDeviceComponents = logDeviceComponents;
	}

}
