package de.bo.aid.boese.model;
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

/**
 * GroupZone generated by hbm2java
 */
public class GroupZone implements java.io.Serializable {

	private GroupZoneId id;
	private Group group;
	private Zone zone;
	private Short rights;

	public GroupZone() {
	}

	public GroupZone(GroupZoneId id, Group group, Zone zone) {
		this.id = id;
		this.group = group;
		this.zone = zone;
	}

	public GroupZone(GroupZoneId id, Group group, Zone zone, Short rights) {
		this.id = id;
		this.group = group;
		this.zone = zone;
		this.rights = rights;
	}

	public GroupZoneId getId() {
		return this.id;
	}

	public void setId(GroupZoneId id) {
		this.id = id;
	}

	public Group getGroup() {
		return this.group;
	}

	public void setGroup(Group group) {
		this.group = group;
	}

	public Zone getZone() {
		return this.zone;
	}

	public void setZone(Zone zone) {
		this.zone = zone;
	}

	public Short getRights() {
		return this.rights;
	}

	public void setRights(Short rights) {
		this.rights = rights;
	}

}
