package de.bo.aid.boese.model;
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

/**
 * GroupUser generated by hbm2java
 */
public class GroupUser implements java.io.Serializable {

	private GroupUserId id;
	private Group group;
	private User user;
	private Short position;

	public GroupUser() {
	}

	public GroupUser(GroupUserId id, Group group, User user) {
		this.id = id;
		this.group = group;
		this.user = user;
	}

	public GroupUser(GroupUserId id, Group group, User user, Short position) {
		this.id = id;
		this.group = group;
		this.user = user;
		this.position = position;
	}

	public GroupUserId getId() {
		return this.id;
	}

	public void setId(GroupUserId id) {
		this.id = id;
	}

	public Group getGroup() {
		return this.group;
	}

	public void setGroup(Group group) {
		this.group = group;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Short getPosition() {
		return this.position;
	}

	public void setPosition(Short position) {
		this.position = position;
	}

}
