

package de.bo.aid.boese.model;
// TODO: Auto-generated Javadoc
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

/**
 * GroupZone generated by hbm2java.
 */
public class GroupZone implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The id. */
	private GroupZoneId id;
	
	/** The group. */
	private Group group;
	
	/** The zone. */
	private Zone zone;
	
	/** The rights. */
	private Short rights;

	/**
	 * Instantiates a new group zone.
	 */
	public GroupZone() {
	}

	/**
	 * Instantiates a new group zone.
	 *
	 * @param id the id
	 * @param group the group
	 * @param zone the zone
	 */
	public GroupZone(GroupZoneId id, Group group, Zone zone) {
		this.id = id;
		this.group = group;
		this.zone = zone;
	}

	/**
	 * Instantiates a new group zone.
	 *
	 * @param id the id
	 * @param group the group
	 * @param zone the zone
	 * @param rights the rights
	 */
	public GroupZone(GroupZoneId id, Group group, Zone zone, Short rights) {
		this.id = id;
		this.group = group;
		this.zone = zone;
		this.rights = rights;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	public GroupZoneId getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(GroupZoneId id) {
		this.id = id;
	}

	/**
	 * Gets the group.
	 *
	 * @return the group
	 */
	public Group getGroup() {
		return this.group;
	}

	/**
	 * Sets the group.
	 *
	 * @param group the new group
	 */
	public void setGroup(Group group) {
		this.group = group;
	}

	/**
	 * Gets the zone.
	 *
	 * @return the zone
	 */
	public Zone getZone() {
		return this.zone;
	}

	/**
	 * Sets the zone.
	 *
	 * @param zone the new zone
	 */
	public void setZone(Zone zone) {
		this.zone = zone;
	}

	/**
	 * Gets the rights.
	 *
	 * @return the rights
	 */
	public Short getRights() {
		return this.rights;
	}

	/**
	 * Sets the rights.
	 *
	 * @param rights the new rights
	 */
	public void setRights(Short rights) {
		this.rights = rights;
	}

}
