
package de.bo.aid.boese.model;
// TODO: Auto-generated Javadoc
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

/**
 * GroupZoneId generated by hbm2java.
 */
public class GroupZoneId implements java.io.Serializable {

	/** The gr id. */
	private short grId;
	
	/** The zo id. */
	private int zoId;

	/**
	 * Instantiates a new group zone id.
	 */
	public GroupZoneId() {
	}

	/**
	 * Instantiates a new group zone id.
	 *
	 * @param grId the gr id
	 * @param zoId the zo id
	 */
	public GroupZoneId(short grId, int zoId) {
		this.grId = grId;
		this.zoId = zoId;
	}

	/**
	 * Gets the gr id.
	 *
	 * @return the gr id
	 */
	public short getGrId() {
		return this.grId;
	}

	/**
	 * Sets the gr id.
	 *
	 * @param grId the new gr id
	 */
	public void setGrId(short grId) {
		this.grId = grId;
	}

	/**
	 * Gets the zo id.
	 *
	 * @return the zo id
	 */
	public int getZoId() {
		return this.zoId;
	}

	/**
	 * Sets the zo id.
	 *
	 * @param zoId the new zo id
	 */
	public void setZoId(int zoId) {
		this.zoId = zoId;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GroupZoneId))
			return false;
		GroupZoneId castOther = (GroupZoneId) other;

		return (this.getGrId() == castOther.getGrId()) && (this.getZoId() == castOther.getZoId());
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGrId();
		result = 37 * result + this.getZoId();
		return result;
	}

}
