/*             
 * 			  (                       
 *			 ( )\         (        (   
 *			 )((_)  (    ))\ (    ))\  
 *			((_)_   )\  /((_))\  /((_) 
 *			 | _ ) ((_)(_)) ((_)(_))   
 *			 | _ \/ _ \/ -_)(_-</ -_)  
 *			 |___/\___/\___|/__/\___|
 *       
 *           			;            
 *		      +        ;;;         + 
 *			  +       ;;;;;        + 
 *			  +      ;;;;;;;       + 
 *			  ++    ;;;;;;;;;     ++ 
 *			  +++++;;;;;;;;;;;+++++  
 *			   ++++;;;;;;;;;;;+++++  
 *				++;;;;;;;;;;;;;++    
 *			     ;;;;;;;;;;;;;;;     
 *			    ;;;;;;;;;;;;;;;;;     
 *				:::::::::::::::::    
 * 				:::::::::::::::::      
 *  			:::::::::::::::::    
 *   			::::::@@@@@::::::    
 *				:::::@:::::@:::::    
 *				::::@:::::::@::::    
 * 				:::::::::::::::::    
 *  			:::::::::::::::::      
 */



package de.bo.aid.boese.model;

// TODO: Auto-generated Javadoc
/**
 * GroupZoneId Model for Hibernate generated by hbm2java.
 */
public class GroupZoneId implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The Group id. */
	private short grId;
	
	/** The Zone id. */
	private int zoId;

	/**
	 * Instantiates a new group zone id.
	 */
	public GroupZoneId() {
	}

	/**
	 * Instantiates a new group zone id.
	 *
	 * @param grId the Group id
	 * @param zoId the Zone id
	 */
	public GroupZoneId(short grId, int zoId) {
		this.grId = grId;
		this.zoId = zoId;
	}

	/**
	 * Gets the Group id.
	 *
	 * @return the Group id
	 */
	public short getGrId() {
		return this.grId;
	}

	/**
	 * Sets the Group id.
	 *
	 * @param grId the new Group id
	 */
	public void setGrId(short grId) {
		this.grId = grId;
	}

	/**
	 * Gets the Zone id.
	 *
	 * @return the Zone id
	 */
	public int getZoId() {
		return this.zoId;
	}

	/**
	 * Sets the Zone id.
	 *
	 * @param zoId the new Zone id
	 */
	public void setZoId(int zoId) {
		this.zoId = zoId;
	}

	/**
	 *  
	 * To compare two GroupZoneIds.
	 *
	 * @param other the GroupZoneId object to compare
	 * @return true if both GroupZoneIds are equal
	 */
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GroupZoneId))
			return false;
		GroupZoneId castOther = (GroupZoneId) other;

		return (this.getGrId() == castOther.getGrId()) && (this.getZoId() == castOther.getZoId());
	}

	/**
	 *  
	 * To create the hashCode.
	 *
	 * @return the hashCode
	 */
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGrId();
		result = 37 * result + this.getZoId();
		return result;
	}
}