package de.bo.aid.boese.model;
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

/**
 * GroupZoneId generated by hbm2java
 */
public class GroupZoneId implements java.io.Serializable {

	private short grId;
	private int zoId;

	public GroupZoneId() {
	}

	public GroupZoneId(short grId, int zoId) {
		this.grId = grId;
		this.zoId = zoId;
	}

	public short getGrId() {
		return this.grId;
	}

	public void setGrId(short grId) {
		this.grId = grId;
	}

	public int getZoId() {
		return this.zoId;
	}

	public void setZoId(int zoId) {
		this.zoId = zoId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GroupZoneId))
			return false;
		GroupZoneId castOther = (GroupZoneId) other;

		return (this.getGrId() == castOther.getGrId()) && (this.getZoId() == castOther.getZoId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGrId();
		result = 37 * result + this.getZoId();
		return result;
	}

}
