/*             
 * 			  (                       
 *			 ( )\         (        (   
 *			 )((_)  (    ))\ (    ))\  
 *			((_)_   )\  /((_))\  /((_) 
 *			 | _ ) ((_)(_)) ((_)(_))   
 *			 | _ \/ _ \/ -_)(_-</ -_)  
 *			 |___/\___/\___|/__/\___|
 *       
 *           			;            
 *		      +        ;;;         + 
 *			  +       ;;;;;        + 
 *			  +      ;;;;;;;       + 
 *			  ++    ;;;;;;;;;     ++ 
 *			  +++++;;;;;;;;;;;+++++  
 *			   ++++;;;;;;;;;;;+++++  
 *				++;;;;;;;;;;;;;++    
 *			     ;;;;;;;;;;;;;;;     
 *			    ;;;;;;;;;;;;;;;;;     
 *				:::::::::::::::::    
 * 				:::::::::::::::::      
 *  			:::::::::::::::::    
 *   			::::::@@@@@::::::    
 *				:::::@:::::@:::::    
 *				::::@:::::::@::::    
 * 				:::::::::::::::::    
 *  			:::::::::::::::::      
 */



package de.bo.aid.boese.model;
// TODO: Auto-generated Javadoc
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

/**
 * GroupUserId Model for Hibernate generated by hbm2java.
 */
public class GroupUserId implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The gr id. */
	private short grId;
	
	/** The us id. */
	private int usId;

	/**
	 * Instantiates a new group user id.
	 */
	public GroupUserId() {
	}

	/**
	 * Instantiates a new group user id.
	 *
	 * @param grId the gr id
	 * @param usId the us id
	 */
	public GroupUserId(short grId, int usId) {
		this.grId = grId;
		this.usId = usId;
	}

	/**
	 * Gets the gr id.
	 *
	 * @return the gr id
	 */
	public short getGrId() {
		return this.grId;
	}

	/**
	 * Sets the gr id.
	 *
	 * @param grId the new gr id
	 */
	public void setGrId(short grId) {
		this.grId = grId;
	}

	/**
	 * Gets the us id.
	 *
	 * @return the us id
	 */
	public int getUsId() {
		return this.usId;
	}

	/**
	 * Sets the us id.
	 *
	 * @param usId the new us id
	 */
	public void setUsId(int usId) {
		this.usId = usId;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GroupUserId))
			return false;
		GroupUserId castOther = (GroupUserId) other;

		return (this.getGrId() == castOther.getGrId()) && (this.getUsId() == castOther.getUsId());
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGrId();
		result = 37 * result + this.getUsId();
		return result;
	}

}
