package de.bo.aid.boese.model;
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

/**
 * GroupUserId generated by hbm2java
 */
public class GroupUserId implements java.io.Serializable {

	private short grId;
	private int usId;

	public GroupUserId() {
	}

	public GroupUserId(short grId, int usId) {
		this.grId = grId;
		this.usId = usId;
	}

	public short getGrId() {
		return this.grId;
	}

	public void setGrId(short grId) {
		this.grId = grId;
	}

	public int getUsId() {
		return this.usId;
	}

	public void setUsId(int usId) {
		this.usId = usId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GroupUserId))
			return false;
		GroupUserId castOther = (GroupUserId) other;

		return (this.getGrId() == castOther.getGrId()) && (this.getUsId() == castOther.getUsId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGrId();
		result = 37 * result + this.getUsId();
		return result;
	}

}
