package de.bo.aid.boese.model;
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;

/**
 * HistoryLogConnector generated by hbm2java
 */
public class HistoryLogConnector implements java.io.Serializable {

	private int hiLoCoId;
	private Connector connector;
	private Date timestap;
	private Serializable data;

	public HistoryLogConnector() {
	}

	public HistoryLogConnector(int hiLoCoId, Connector connector, Date timestap, Serializable data) {
		this.hiLoCoId = hiLoCoId;
		this.connector = connector;
		this.timestap = timestap;
		this.data = data;
	}

	public int getHiLoCoId() {
		return this.hiLoCoId;
	}

	public void setHiLoCoId(int hiLoCoId) {
		this.hiLoCoId = hiLoCoId;
	}

	public Connector getConnector() {
		return this.connector;
	}

	public void setConnector(Connector connector) {
		this.connector = connector;
	}

	public Date getTimestap() {
		return this.timestap;
	}

	public void setTimestap(Date timestap) {
		this.timestap = timestap;
	}

	public Serializable getData() {
		return this.data;
	}

	public void setData(Serializable data) {
		this.data = data;
	}

}
