package de.bo.aid.boese.model;
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * HistoryLogComponent generated by hbm2java
 */
public class HistoryLogComponent implements java.io.Serializable {

	private int hiLoCoId;
	private Date timestamp;
	private DeviceComponent deviceComponent;
	private BigDecimal value;

	public HistoryLogComponent() {
	}

	public HistoryLogComponent(int hiLoCoId, DeviceComponent deviceComponent, BigDecimal value) {
		this.hiLoCoId = hiLoCoId;
		this.deviceComponent = deviceComponent;
		this.value = value;
	}

	public int getHiLoCoId() {
		return this.hiLoCoId;
	}

	public void setHiLoCoId(int hiLoCoId) {
		this.hiLoCoId = hiLoCoId;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public DeviceComponent getDeviceComponent() {
		return this.deviceComponent;
	}

	public void setDeviceComponent(DeviceComponent deviceComponent) {
		this.deviceComponent = deviceComponent;
	}

	public BigDecimal getValue() {
		return this.value;
	}

	public void setValue(BigDecimal value) {
		this.value = value;
	}

}
