package de.bo.aid.boese.model;
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * HistoryLogRule generated by hbm2java
 */
public class HistoryLogRule implements java.io.Serializable {

	private int hiLoRuId;
	private Date timestamp;
	private Rule rule;

	public HistoryLogRule() {
	}

	public HistoryLogRule(int hiLoRuId, Rule rule) {
		this.hiLoRuId = hiLoRuId;
		this.rule = rule;
	}

	public int getHiLoRuId() {
		return this.hiLoRuId;
	}

	public void setHiLoRuId(int hiLoRuId) {
		this.hiLoRuId = hiLoRuId;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public Rule getRule() {
		return this.rule;
	}

	public void setRule(Rule rule) {
		this.rule = rule;
	}

}
