/*             
 * 			  (                       
 *			 ( )\         (        (   
 *			 )((_)  (    ))\ (    ))\  
 *			((_)_   )\  /((_))\  /((_) 
 *			 | _ ) ((_)(_)) ((_)(_))   
 *			 | _ \/ _ \/ -_)(_-</ -_)  
 *			 |___/\___/\___|/__/\___|
 *       
 *           			;            
 *		      +        ;;;         + 
 *			  +       ;;;;;        + 
 *			  +      ;;;;;;;       + 
 *			  ++    ;;;;;;;;;     ++ 
 *			  +++++;;;;;;;;;;;+++++  
 *			   ++++;;;;;;;;;;;+++++  
 *				++;;;;;;;;;;;;;++    
 *			     ;;;;;;;;;;;;;;;     
 *			    ;;;;;;;;;;;;;;;;;     
 *				:::::::::::::::::    
 * 				:::::::::::::::::      
 *  			:::::::::::::::::    
 *   			::::::@@@@@::::::    
 *				:::::@:::::@:::::    
 *				::::@:::::::@::::    
 * 				:::::::::::::::::    
 *  			:::::::::::::::::      
 */


package de.bo.aid.boese.model;
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;

// TODO: Auto-generated Javadoc
/**
 * HistoryLogConnector generated by hbm2java.
 */
public class HistoryLogConnector implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The hi lo co id. */
	private int hiLoCoId;
	
	/** The connector. */
	private Connector connector;
	
	/** The timestap. */
	private Date timestap;
	
	/** The data. */
	private Serializable data;

	/**
	 * Instantiates a new history log connector.
	 */
	public HistoryLogConnector() {
	}

	/**
	 * Instantiates a new history log connector.
	 *
	 * @param hiLoCoId the hi lo co id
	 * @param connector the connector
	 * @param timestap the timestap
	 * @param data the data
	 */
	public HistoryLogConnector(int hiLoCoId, Connector connector, Date timestap, Serializable data) {
		this.hiLoCoId = hiLoCoId;
		this.connector = connector;
		this.timestap = timestap;
		this.data = data;
	}

	/**
	 * Gets the hi lo co id.
	 *
	 * @return the hi lo co id
	 */
	public int getHiLoCoId() {
		return this.hiLoCoId;
	}

	/**
	 * Sets the hi lo co id.
	 *
	 * @param hiLoCoId the new hi lo co id
	 */
	public void setHiLoCoId(int hiLoCoId) {
		this.hiLoCoId = hiLoCoId;
	}

	/**
	 * Gets the connector.
	 *
	 * @return the connector
	 */
	public Connector getConnector() {
		return this.connector;
	}

	/**
	 * Sets the connector.
	 *
	 * @param connector the new connector
	 */
	public void setConnector(Connector connector) {
		this.connector = connector;
	}

	/**
	 * Gets the timestap.
	 *
	 * @return the timestap
	 */
	public Date getTimestap() {
		return this.timestap;
	}

	/**
	 * Sets the timestap.
	 *
	 * @param timestap the new timestap
	 */
	public void setTimestap(Date timestap) {
		this.timestap = timestap;
	}

	/**
	 * Gets the data.
	 *
	 * @return the data
	 */
	public Serializable getData() {
		return this.data;
	}

	/**
	 * Sets the data.
	 *
	 * @param data the new data
	 */
	public void setData(Serializable data) {
		this.data = data;
	}

}
