


package de.bo.aid.boese.model;
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;

// TODO: Auto-generated Javadoc
/**
 * LogConnector generated by hbm2java.
 */
public class LogConnector implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The lo co id. */
	private int loCoId;
	
	/** The connector. */
	private Connector connector;
	
	/** The timestap. */
	private Date timestap;
	
	/** The data. */
	private Serializable data;

	/**
	 * Instantiates a new log connector.
	 */
	public LogConnector() {
	}

	/**
	 * Instantiates a new log connector.
	 *
	 * @param loCoId the lo co id
	 * @param connector the connector
	 * @param timestap the timestap
	 * @param data the data
	 */
	public LogConnector(int loCoId, Connector connector, Date timestap, Serializable data) {
		this.loCoId = loCoId;
		this.connector = connector;
		this.timestap = timestap;
		this.data = data;
	}

	/**
	 * Gets the lo co id.
	 *
	 * @return the lo co id
	 */
	public int getLoCoId() {
		return this.loCoId;
	}

	/**
	 * Sets the lo co id.
	 *
	 * @param loCoId the new lo co id
	 */
	public void setLoCoId(int loCoId) {
		this.loCoId = loCoId;
	}

	/**
	 * Gets the connector.
	 *
	 * @return the connector
	 */
	public Connector getConnector() {
		return this.connector;
	}

	/**
	 * Sets the connector.
	 *
	 * @param connector the new connector
	 */
	public void setConnector(Connector connector) {
		this.connector = connector;
	}

	/**
	 * Gets the timestap.
	 *
	 * @return the timestap
	 */
	public Date getTimestap() {
		return this.timestap;
	}

	/**
	 * Sets the timestap.
	 *
	 * @param timestap the new timestap
	 */
	public void setTimestap(Date timestap) {
		this.timestap = timestap;
	}

	/**
	 * Gets the data.
	 *
	 * @return the data
	 */
	public Serializable getData() {
		return this.data;
	}

	/**
	 * Sets the data.
	 *
	 * @param data the new data
	 */
	public void setData(Serializable data) {
		this.data = data;
	}

}
