package de.bo.aid.boese.model;
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * LogComponent generated by hbm2java
 */
public class LogComponent implements java.io.Serializable {

	private int loCoId;
	private Date timestamp;
	private DeviceComponent deviceComponent;
	private BigDecimal value;

	public LogComponent() {
	}

	public LogComponent(int loCoId, DeviceComponent deviceComponent, BigDecimal value) {
		this.loCoId = loCoId;
		this.deviceComponent = deviceComponent;
		this.value = value;
	}

	public int getLoCoId() {
		return this.loCoId;
	}

	public void setLoCoId(int loCoId) {
		this.loCoId = loCoId;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public DeviceComponent getDeviceComponent() {
		return this.deviceComponent;
	}

	public void setDeviceComponent(DeviceComponent deviceComponent) {
		this.deviceComponent = deviceComponent;
	}

	public BigDecimal getValue() {
		return this.value;
	}

	public void setValue(BigDecimal value) {
		this.value = value;
	}

}
