/*             
 * 			  (                       
 *			 ( )\         (        (   
 *			 )((_)  (    ))\ (    ))\  
 *			((_)_   )\  /((_))\  /((_) 
 *			 | _ ) ((_)(_)) ((_)(_))   
 *			 | _ \/ _ \/ -_)(_-</ -_)  
 *			 |___/\___/\___|/__/\___|
 *       
 *           			;            
 *		      +        ;;;         + 
 *			  +       ;;;;;        + 
 *			  +      ;;;;;;;       + 
 *			  ++    ;;;;;;;;;     ++ 
 *			  +++++;;;;;;;;;;;+++++  
 *			   ++++;;;;;;;;;;;+++++  
 *				++;;;;;;;;;;;;;++    
 *			     ;;;;;;;;;;;;;;;     
 *			    ;;;;;;;;;;;;;;;;;     
 *				:::::::::::::::::    
 * 				:::::::::::::::::      
 *  			:::::::::::::::::    
 *   			::::::@@@@@::::::    
 *				:::::@:::::@:::::    
 *				::::@:::::::@::::    
 * 				:::::::::::::::::    
 *  			:::::::::::::::::      
 */



package de.bo.aid.boese.model;
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

// TODO: Auto-generated Javadoc
/**
 * LogDeviceComponent generated by hbm2java.
 */
public class LogDeviceComponent implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The lo co id. */
	private int loCoId;
	
	/** The timestamp. */
	private Date timestamp;
	
	/** The device component. */
	private DeviceComponent deviceComponent;
	
	/** The value. */
	private BigDecimal value;

	/**
	 * Instantiates a new log device component.
	 */
	public LogDeviceComponent() {
	}

	/**
	 * Instantiates a new log device component.
	 *
	 * @param loCoId the lo co id
	 * @param deviceComponent the device component
	 * @param value the value
	 */
	public LogDeviceComponent(int loCoId, DeviceComponent deviceComponent, BigDecimal value) {
		this.loCoId = loCoId;
		this.deviceComponent = deviceComponent;
		this.value = value;
	}

	/**
	 * Gets the lo co id.
	 *
	 * @return the lo co id
	 */
	public int getLoCoId() {
		return this.loCoId;
	}

	/**
	 * Sets the lo co id.
	 *
	 * @param loCoId the new lo co id
	 */
	public void setLoCoId(int loCoId) {
		this.loCoId = loCoId;
	}

	/**
	 * Gets the timestamp.
	 *
	 * @return the timestamp
	 */
	public Date getTimestamp() {
		return this.timestamp;
	}

	/**
	 * Sets the timestamp.
	 *
	 * @param timestamp the new timestamp
	 */
	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	/**
	 * Gets the device component.
	 *
	 * @return the device component
	 */
	public DeviceComponent getDeviceComponent() {
		return this.deviceComponent;
	}

	/**
	 * Sets the device component.
	 *
	 * @param deviceComponent the new device component
	 */
	public void setDeviceComponent(DeviceComponent deviceComponent) {
		this.deviceComponent = deviceComponent;
	}

	/**
	 * Gets the value.
	 *
	 * @return the value
	 */
	public BigDecimal getValue() {
		return this.value;
	}

	/**
	 * Sets the value.
	 *
	 * @param value the new value
	 */
	public void setValue(BigDecimal value) {
		this.value = value;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		LogDeviceComponent other = (LogDeviceComponent) obj;
		if (deviceComponent == null) {
			if (other.deviceComponent != null)
				return false;
		} else if (!deviceComponent.equals(other.deviceComponent))
			return false;
		if (loCoId != other.loCoId)
			return false;
		if (timestamp == null) {
			if (other.timestamp != null)
				return false;
		} else if (!timestamp.equals(other.timestamp))
			return false;
		if (value == null) {
			if (other.value != null)
				return false;
		} else if (!value.equals(other.value))
			return false;
		return true;
	}

}
