
package de.bo.aid.boese.model;
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

import java.util.Date;

// TODO: Auto-generated Javadoc
/**
 * LogRule generated by hbm2java.
 */
public class LogRule implements java.io.Serializable {

	/** The lo ru id. */
	private int loRuId;
	
	/** The timestamp. */
	private Date timestamp;
	
	/** The rule. */
	private Rule rule;

	/**
	 * Instantiates a new log rule.
	 */
	public LogRule() {
	}

	/**
	 * Instantiates a new log rule.
	 *
	 * @param loRuId the lo ru id
	 * @param rule the rule
	 */
	public LogRule(int loRuId, Rule rule) {
		this.loRuId = loRuId;
		this.rule = rule;
	}

	/**
	 * Gets the lo ru id.
	 *
	 * @return the lo ru id
	 */
	public int getLoRuId() {
		return this.loRuId;
	}

	/**
	 * Sets the lo ru id.
	 *
	 * @param loRuId the new lo ru id
	 */
	public void setLoRuId(int loRuId) {
		this.loRuId = loRuId;
	}

	/**
	 * Gets the timestamp.
	 *
	 * @return the timestamp
	 */
	public Date getTimestamp() {
		return this.timestamp;
	}

	/**
	 * Sets the timestamp.
	 *
	 * @param timestamp the new timestamp
	 */
	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	/**
	 * Gets the rule.
	 *
	 * @return the rule
	 */
	public Rule getRule() {
		return this.rule;
	}

	/**
	 * Sets the rule.
	 *
	 * @param rule the new rule
	 */
	public void setRule(Rule rule) {
		this.rule = rule;
	}

}
