package de.bo.aid.boese.model;
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * LogRule generated by hbm2java
 */
public class LogRule implements java.io.Serializable {

	private int loRuId;
	private Date timestamp;
	private Rule rule;

	public LogRule() {
	}

	public LogRule(int loRuId, Rule rule) {
		this.loRuId = loRuId;
		this.rule = rule;
	}

	public int getLoRuId() {
		return this.loRuId;
	}

	public void setLoRuId(int loRuId) {
		this.loRuId = loRuId;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public Rule getRule() {
		return this.rule;
	}

	public void setRule(Rule rule) {
		this.rule = rule;
	}

}
