package de.bo.aid.boese.model;
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Rule generated by hbm2java
 */
public class Rule implements java.io.Serializable {

	private int ruId;
	private Boolean active;
	private Date insertDate;
	private Date modifyDate;
	private Serializable permissions;
	private Serializable conditions;
	private Serializable actions;
	private Set logRules = new HashSet(0);
	private Set historyLogRules = new HashSet(0);

	public Rule() {
	}

	public Rule(int ruId) {
		this.ruId = ruId;
	}

	public Rule(int ruId, Boolean active, Date insertDate, Date modifyDate, Serializable permissions,
			Serializable conditions, Serializable actions, Set logRules, Set historyLogRules) {
		this.ruId = ruId;
		this.active = active;
		this.insertDate = insertDate;
		this.modifyDate = modifyDate;
		this.permissions = permissions;
		this.conditions = conditions;
		this.actions = actions;
		this.logRules = logRules;
		this.historyLogRules = historyLogRules;
	}

	public int getRuId() {
		return this.ruId;
	}

	public void setRuId(int ruId) {
		this.ruId = ruId;
	}

	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public Serializable getPermissions() {
		return this.permissions;
	}

	public void setPermissions(Serializable permissions) {
		this.permissions = permissions;
	}

	public Serializable getConditions() {
		return this.conditions;
	}

	public void setConditions(Serializable conditions) {
		this.conditions = conditions;
	}

	public Serializable getActions() {
		return this.actions;
	}

	public void setActions(Serializable actions) {
		this.actions = actions;
	}

	public Set getLogRules() {
		return this.logRules;
	}

	public void setLogRules(Set logRules) {
		this.logRules = logRules;
	}

	public Set getHistoryLogRules() {
		return this.historyLogRules;
	}

	public void setHistoryLogRules(Set historyLogRules) {
		this.historyLogRules = historyLogRules;
	}

}
