package de.bo.aid.boese.model;
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Service generated by hbm2java
 */
public class Service implements java.io.Serializable {

	private int seId;
	private String description;
	private Set devices = new HashSet(0);

	public Service() {
	}

	public Service(int seId, String description) {
		this.seId = seId;
		this.description = description;
	}

	public Service(int seId, String description, Set devices) {
		this.seId = seId;
		this.description = description;
		this.devices = devices;
	}

	public int getSeId() {
		return this.seId;
	}

	public void setSeId(int seId) {
		this.seId = seId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getDevices() {
		return this.devices;
	}

	public void setDevices(Set devices) {
		this.devices = devices;
	}

}
