package de.bo.aid.boese.model;
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Unit generated by hbm2java
 */
public class Unit implements java.io.Serializable {

	private int unId;
	private String name;
	private String symbol;
	private Set components = new HashSet(0);

	public Unit() {
	}

	public Unit(int unId) {
		this.unId = unId;
	}

	public Unit(int unId, String name, String symbol, Set components) {
		this.unId = unId;
		this.name = name;
		this.symbol = symbol;
		this.components = components;
	}

	public int getUnId() {
		return this.unId;
	}

	public void setUnId(int unId) {
		this.unId = unId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	public Set getComponents() {
		return this.components;
	}

	public void setComponents(Set components) {
		this.components = components;
	}

}
