package de.bo.aid.boese.model;
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private int usId;
	private String surname;
	private String firstName;
	private String password;
	private Boolean gender;
	private Date birthdate;
	private String userName;
	private String email;
	private Set groupUsers = new HashSet(0);

	public User() {
	}

	public User(int usId, String surname, String firstName, String password, String userName) {
		this.usId = usId;
		this.surname = surname;
		this.firstName = firstName;
		this.password = password;
		this.userName = userName;
	}

	public User(int usId, String surname, String firstName, String password, Boolean gender, Date birthdate,
			String userName, String email, Set groupUsers) {
		this.usId = usId;
		this.surname = surname;
		this.firstName = firstName;
		this.password = password;
		this.gender = gender;
		this.birthdate = birthdate;
		this.userName = userName;
		this.email = email;
		this.groupUsers = groupUsers;
	}

	public int getUsId() {
		return this.usId;
	}

	public void setUsId(int usId) {
		this.usId = usId;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Boolean getGender() {
		return this.gender;
	}

	public void setGender(Boolean gender) {
		this.gender = gender;
	}

	public Date getBirthdate() {
		return this.birthdate;
	}

	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getGroupUsers() {
		return this.groupUsers;
	}

	public void setGroupUsers(Set groupUsers) {
		this.groupUsers = groupUsers;
	}

}
