/*             
 * 			  (                       
 *			 ( )\         (        (   
 *			 )((_)  (    ))\ (    ))\  
 *			((_)_   )\  /((_))\  /((_) 
 *			 | _ ) ((_)(_)) ((_)(_))   
 *			 | _ \/ _ \/ -_)(_-</ -_)  
 *			 |___/\___/\___|/__/\___|
 *       
 *           			;            
 *		      +        ;;;         + 
 *			  +       ;;;;;        + 
 *			  +      ;;;;;;;       + 
 *			  ++    ;;;;;;;;;     ++ 
 *			  +++++;;;;;;;;;;;+++++  
 *			   ++++;;;;;;;;;;;+++++  
 *				++;;;;;;;;;;;;;++    
 *			     ;;;;;;;;;;;;;;;     
 *			    ;;;;;;;;;;;;;;;;;     
 *				:::::::::::::::::    
 * 				:::::::::::::::::      
 *  			:::::::::::::::::    
 *   			::::::@@@@@::::::    
 *				:::::@:::::@:::::    
 *				::::@:::::::@::::    
 * 				:::::::::::::::::    
 *  			:::::::::::::::::      
 */



package de.bo.aid.boese.model;
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

// TODO: Auto-generated Javadoc
/**
 * Zone generated by hbm2java.
 */
public class Zone implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The zo id. */
	private int zoId;
	
	/** The zone. */
	private Zone zone;
	
	/** The name. */
	private String name;
	
	/** The group zones. */
	private Set<GroupZone> groupZones = new HashSet<GroupZone>(0);
	
	/** The zones. */
	private Set<Zone> zones = new HashSet<Zone>(0);
	
	/** The devices. */
	private Set<Device> devices = new HashSet<Device>(0);

	/**
	 * Instantiates a new zone.
	 */
	public Zone() {
	
	}

	/**
	 * Instantiates a new zone for DB Insert.
	 *
	 * @param name the name
	 */
	public Zone(String name) {
		this.name = name;
	}

	/**
	 * Instantiates a new zone.
	 *
	 * @param zoId the zo id
	 * @param zone the zone
	 * @param name the name
	 */
	public Zone(int zoId, Zone zone, String name) {
		this.zoId = zoId;
		this.zone = zone;
		this.name = name;
	}

	/**
	 * Instantiates a new zone.
	 *
	 * @param zoId the zo id
	 * @param zone the zone
	 * @param name the name
	 * @param groupZones the group zones
	 * @param zones the zones
	 * @param devices the devices
	 */
	public Zone(int zoId, Zone zone, String name, Set<GroupZone> groupZones, Set<Zone> zones, Set<Device> devices) {
		this.zoId = zoId;
		this.zone = zone;
		this.name = name;
		this.groupZones = groupZones;
		this.zones = zones;
		this.devices = devices;
	}

	/**
	 * Gets the zo id.
	 *
	 * @return the zo id
	 */
	public int getZoId() {
		return this.zoId;
	}

	/**
	 * Sets the zo id.
	 *
	 * @param zoId the new zo id
	 */
	public void setZoId(int zoId) {
		this.zoId = zoId;
	}

	/**
	 * Gets the zone.
	 *
	 * @return the zone
	 */
	public Zone getZone() {
		return this.zone;
	}

	/**
	 * Sets the zone.
	 *
	 * @param zone the new zone
	 */
	public void setZone(Zone zone) {
		this.zone = zone;
	}

	/**
	 * Gets the name.
	 *
	 * @return the name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Sets the name.
	 *
	 * @param name the new name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Gets the group zones.
	 *
	 * @return the group zones
	 */
	public Set<GroupZone> getGroupZones() {
		return this.groupZones;
	}

	/**
	 * Sets the group zones.
	 *
	 * @param groupZones the new group zones
	 */
	public void setGroupZones(Set<GroupZone> groupZones) {
		this.groupZones = groupZones;
	}

	/**
	 * Gets the zones.
	 *
	 * @return the zones
	 */
	public Set<Zone> getZones() {
		return this.zones;
	}

	/**
	 * Sets the zones.
	 *
	 * @param zones the new zones
	 */
	public void setZones(Set<Zone> zones) {
		this.zones = zones;
	}

	/**
	 * Gets the devices.
	 *
	 * @return the devices
	 */
	public Set<Device> getDevices() {
		return this.devices;
	}

	/**
	 * Sets the devices.
	 *
	 * @param devices the new devices
	 */
	public void setDevices(Set<Device> devices) {
		this.devices = devices;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Zone other = (Zone) obj;
		if (devices == null) {
			if (other.devices != null)
				return false;
		} else if (!devices.equals(other.devices))
			return false;
		if (groupZones == null) {
			if (other.groupZones != null)
				return false;
		} else if (!groupZones.equals(other.groupZones))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (zoId != other.zoId)
			return false;
		if (zone == null) {
			if (other.zone != null)
				return false;
		} else if (!zone.equals(other.zone))
			return false;
		if (zones == null) {
			if (other.zones != null)
				return false;
		} else if (!zones.equals(other.zones))
			return false;
		return true;
	}

}
