package de.bo.aid.boese.model;
// Generated 30.07.2015 11:14:41 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Zone generated by hbm2java
 */
public class Zone implements java.io.Serializable {

	private int zoId;
	private Zone zone;
	private String name;
	private Set groupZones = new HashSet(0);
	private Set zones = new HashSet(0);
	private Set devices = new HashSet(0);

	public Zone() {
	}

	public Zone(int zoId, Zone zone, String name) {
		this.zoId = zoId;
		this.zone = zone;
		this.name = name;
	}

	public Zone(int zoId, Zone zone, String name, Set groupZones, Set zones, Set devices) {
		this.zoId = zoId;
		this.zone = zone;
		this.name = name;
		this.groupZones = groupZones;
		this.zones = zones;
		this.devices = devices;
	}

	public int getZoId() {
		return this.zoId;
	}

	public void setZoId(int zoId) {
		this.zoId = zoId;
	}

	public Zone getZone() {
		return this.zone;
	}

	public void setZone(Zone zone) {
		this.zone = zone;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getGroupZones() {
		return this.groupZones;
	}

	public void setGroupZones(Set groupZones) {
		this.groupZones = groupZones;
	}

	public Set getZones() {
		return this.zones;
	}

	public void setZones(Set zones) {
		this.zones = zones;
	}

	public Set getDevices() {
		return this.devices;
	}

	public void setDevices(Set devices) {
		this.devices = devices;
	}

}
